<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>App.Main.ico</ApplicationIcon>
    <AssemblyTitle>Panama ∑en</AssemblyTitle>
    <Company>Restless Animal Development</Company>
    <Copyright>(c) 2020-2025 Restless Animal Development</Copyright>
    <Description>Provides overall tracking services for titles (date written, updated, multiple version support, search, analysis), publications, submissions, associated submission documents and submission email messages.</Description>
    <OutputType>WinExe</OutputType>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/victor-david/panama</PackageProjectUrl>
    <Product>Panama</Product>
    <RepositoryUrl>https://github.com/victor-david/panama</RepositoryUrl>
    <RootNamespace>Restless.Panama</RootNamespace>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Version>5.0.15</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="5.1.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.PhosphorIcons" Version="5.1.0" />
    <PackageReference Include="MimeKitLite" Version="4.7.1" />
    <PackageReference Include="Restless.Toolkit" Version="2.5.25" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
    <PackageReference Include="System.Data.OleDb" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Panama.Controls\Panama.Controls.csproj" />
    <ProjectReference Include="..\Panama.Database\Panama.Database.csproj" />
    <ProjectReference Include="..\Panama.Network\Panama.Network.csproj" />
    <ProjectReference Include="..\Panama.Resources\Panama.Resources.csproj" />
    <ProjectReference Include="..\Panama.Utility\Panama.Utility.csproj" />
  </ItemGroup>

</Project>