//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.App.Panama.Database.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.App.Panama.Database.Resources.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;author&quot; (&quot;id&quot;, &quot;name&quot;, &quot;isdefault&quot;) VALUES (1, &apos;Your Author Name&apos;, 1);.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;documenttype&quot; (&quot;id&quot;, &quot;name&quot;, &quot;extensions&quot;, &quot;ordering&quot;, &quot;supported&quot;) VALUES (0, &apos;Unknown&apos;, NULL, 100, 0);
        ///INSERT INTO &quot;documenttype&quot; (&quot;id&quot;, &quot;name&quot;, &quot;extensions&quot;, &quot;ordering&quot;, &quot;supported&quot;) VALUES (1, &apos;Word Document (OpenXml)&apos;, &apos;.docx&apos;, 1, 1);
        ///INSERT INTO &quot;documenttype&quot; (&quot;id&quot;, &quot;name&quot;, &quot;extensions&quot;, &quot;ordering&quot;, &quot;supported&quot;) VALUES (2, &apos;Word Document (Old)&apos;, &apos;.doc;.rtf&apos;, 2, 1);
        ///INSERT INTO &quot;documenttype&quot; (&quot;id&quot;, &quot;name&quot;, &quot;extensions&quot;, &quot;ordering&quot;, &quot;supported&quot;) VALUES (3, &apos;Pdf Document&apos;, &apos;.pdf&apos;, 3, 1) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;language&quot; (&quot;id&quot;, &quot;name&quot;) VALUES (&apos;en-us&apos;, &apos;English (US)&apos;);
        ///INSERT INTO &quot;language&quot; (&quot;id&quot;, &quot;name&quot;) VALUES (&apos;es-mx&apos;, &apos;Spanish (Mexico)&apos;);.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;response&quot; (&quot;id&quot;, &quot;name&quot;, &quot;description&quot;) VALUES (0, NULL, &apos;None. The submission has not yet received a response.&apos;);
        ///INSERT INTO &quot;response&quot; (&quot;id&quot;, &quot;name&quot;, &quot;description&quot;) VALUES (1, &apos;(not specified)&apos;, &apos;Not Specified. The response type has not been specified.&apos;);
        ///INSERT INTO &quot;response&quot; (&quot;id&quot;, &quot;name&quot;, &quot;description&quot;) VALUES (2, &apos;BFN&apos;, &apos;Form Rejection. Standard BFN note. No personalization. No encouragement.&apos;);
        ///INSERT INTO &quot;response&quot; (&quot;id&quot;, &quot;name&quot;, &quot;description&quot;) VALUES (3, &apos;Try Again&apos;, &apos;A rejection [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;schema&quot; (&quot;id&quot;, &quot;version&quot;, &quot;ts&quot;) VALUES (1, 100, &apos;2017-02-01 00:00:00&apos;);.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
    }
}
