//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.App.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.App.Panama.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occured.
        ///
        ///{0}
        ///
        ///The application cannot continue..
        /// </summary>
        public static string ApplicationFatalExceptionFormat {
            get {
                return ResourceManager.GetString("ApplicationFatalExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string CaptionFatalError {
            get {
                return ResourceManager.GetString("CaptionFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons designed by Linear Color SEO (Freepik), Smashicons, Swifticons, and Maxim Basinski from Flaticon.
        /// </summary>
        public static string CaptionIconsDesigned1 {
            get {
                return ResourceManager.GetString("CaptionIconsDesigned1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder to be used for submission messages.
        /// </summary>
        public static string CaptionSelectMapiFolder {
            get {
                return ResourceManager.GetString("CaptionSelectMapiFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a submission document.
        /// </summary>
        public static string CaptionSelectSubmissionDocument {
            get {
                return ResourceManager.GetString("CaptionSelectSubmissionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the message(s) to add to this submission.
        /// </summary>
        public static string CaptionSelectSubmissionMessage {
            get {
                return ResourceManager.GetString("CaptionSelectSubmissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder to filter the title list by.
        /// </summary>
        public static string CaptionSelectTitleFilterFolder {
            get {
                return ResourceManager.GetString("CaptionSelectTitleFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to add to the versions of this title.
        /// </summary>
        public static string CaptionSelectTitleVersionAddByFile {
            get {
                return ResourceManager.GetString("CaptionSelectTitleVersionAddByFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to replace the file of the selected version.
        /// </summary>
        public static string CaptionSelectTitleVersionReplaceByFile {
            get {
                return ResourceManager.GetString("CaptionSelectTitleVersionReplaceByFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add author.
        /// </summary>
        public static string CommandAddAuthor {
            get {
                return ResourceManager.GetString("CommandAddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new author.
        /// </summary>
        public static string CommandAddAuthorTooltip {
            get {
                return ResourceManager.GetString("CommandAddAuthorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add credential.
        /// </summary>
        public static string CommandAddCredential {
            get {
                return ResourceManager.GetString("CommandAddCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a credential set.
        /// </summary>
        public static string CommandAddCredentialTooltip {
            get {
                return ResourceManager.GetString("CommandAddCredentialTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link.
        /// </summary>
        public static string CommandAddLink {
            get {
                return ResourceManager.GetString("CommandAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a link to a resource.
        /// </summary>
        public static string CommandAddLinkTooltip {
            get {
                return ResourceManager.GetString("CommandAddLinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add publisher.
        /// </summary>
        public static string CommandAddPublisher {
            get {
                return ResourceManager.GetString("CommandAddPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new publisher to the list.
        /// </summary>
        public static string CommandAddPublisherTooltip {
            get {
                return ResourceManager.GetString("CommandAddPublisherTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add submission.
        /// </summary>
        public static string CommandAddSubmission {
            get {
                return ResourceManager.GetString("CommandAddSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new submission.
        /// </summary>
        public static string CommandAddSubmissionTooltip {
            get {
                return ResourceManager.GetString("CommandAddSubmissionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a tag.
        /// </summary>
        public static string CommandAddTag {
            get {
                return ResourceManager.GetString("CommandAddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a tag to be used with titles.
        /// </summary>
        public static string CommandAddTagTooltip {
            get {
                return ResourceManager.GetString("CommandAddTagTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add title.
        /// </summary>
        public static string CommandAddTitle {
            get {
                return ResourceManager.GetString("CommandAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new title to the list.
        /// </summary>
        public static string CommandAddTitleTooltip {
            get {
                return ResourceManager.GetString("CommandAddTitleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this title to a submission.
        /// </summary>
        public static string CommandAddTitleToSubmission {
            get {
                return ResourceManager.GetString("CommandAddTitleToSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        public static string CommandAddUserNote {
            get {
                return ResourceManager.GetString("CommandAddUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new note.
        /// </summary>
        public static string CommandAddUserNoteTooltip {
            get {
                return ResourceManager.GetString("CommandAddUserNoteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string CommandApplyConfig {
            get {
                return ResourceManager.GetString("CommandApplyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the changed application settings.
        /// </summary>
        public static string CommandApplyConfigTooltip {
            get {
                return ResourceManager.GetString("CommandApplyConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string CommandAuthor {
            get {
                return ResourceManager.GetString("CommandAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to this publisher&apos;s web site.
        /// </summary>
        public static string CommandBrowseToPublisherUrl {
            get {
                return ResourceManager.GetString("CommandBrowseToPublisherUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to this publisher&apos;s web site (or double click the row).
        /// </summary>
        public static string CommandBrowseToPublisherUrlOrClick {
            get {
                return ResourceManager.GetString("CommandBrowseToPublisherUrlOrClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to this url (or double click the row).
        /// </summary>
        public static string CommandBrowseToUrlOrClick {
            get {
                return ResourceManager.GetString("CommandBrowseToUrlOrClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CommandClearFilter {
            get {
                return ResourceManager.GetString("CommandClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filters.
        /// </summary>
        public static string CommandClearFilterTooltip {
            get {
                return ResourceManager.GetString("CommandClearFilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string CommandConfig {
            get {
                return ResourceManager.GetString("CommandConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and modify application settings.
        /// </summary>
        public static string CommandConfigTooltip {
            get {
                return ResourceManager.GetString("CommandConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy login id to clipboard.
        /// </summary>
        public static string CommandCopyLoginId {
            get {
                return ResourceManager.GetString("CommandCopyLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password to clipboard.
        /// </summary>
        public static string CommandCopyPassword {
            get {
                return ResourceManager.GetString("CommandCopyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a submission to this publisher.
        /// </summary>
        public static string CommandCreateSubmission {
            get {
                return ResourceManager.GetString("CommandCreateSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string CommandCredential {
            get {
                return ResourceManager.GetString("CommandCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this author.
        /// </summary>
        public static string CommandDeleteAuthor {
            get {
                return ResourceManager.GetString("CommandDeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this credential.
        /// </summary>
        public static string CommandDeleteCredential {
            get {
                return ResourceManager.GetString("CommandDeleteCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this link.
        /// </summary>
        public static string CommandDeleteLink {
            get {
                return ResourceManager.GetString("CommandDeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this note.
        /// </summary>
        public static string CommandDeleteNote {
            get {
                return ResourceManager.GetString("CommandDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this publisher.
        /// </summary>
        public static string CommandDeletePublisher {
            get {
                return ResourceManager.GetString("CommandDeletePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this submission.
        /// </summary>
        public static string CommandDeleteSubmission {
            get {
                return ResourceManager.GetString("CommandDeleteSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this tag.
        /// </summary>
        public static string CommandDeleteTag {
            get {
                return ResourceManager.GetString("CommandDeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this title.
        /// </summary>
        public static string CommandDeleteTitle {
            get {
                return ResourceManager.GetString("CommandDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this note.
        /// </summary>
        public static string CommandDeleteUserNote {
            get {
                return ResourceManager.GetString("CommandDeleteUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter list to display only submissions to this publisher.
        /// </summary>
        public static string CommandFilterToPublisher {
            get {
                return ResourceManager.GetString("CommandFilterToPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string CommandLink {
            get {
                return ResourceManager.GetString("CommandLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this item (or double click the row).
        /// </summary>
        public static string CommandOpenItemOrDoubleClick {
            get {
                return ResourceManager.GetString("CommandOpenItemOrDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the latest version of this title (or double click the row).
        /// </summary>
        public static string CommandOpenTitleOrDoubleClick {
            get {
                return ResourceManager.GetString("CommandOpenTitleOrDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string CommandPublisher {
            get {
                return ResourceManager.GetString("CommandPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage existing publishers, create new publishers, etc..
        /// </summary>
        public static string CommandPublisherTooltip {
            get {
                return ResourceManager.GetString("CommandPublisherTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh usage.
        /// </summary>
        public static string CommandRefreshTagUsage {
            get {
                return ResourceManager.GetString("CommandRefreshTagUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh tag usage. This gets automatically refreshed when you restart the application, but you can do it manually if needed.
        /// </summary>
        public static string CommandRefreshTagUsageTooltip {
            get {
                return ResourceManager.GetString("CommandRefreshTagUsageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string CommandRevertConfig {
            get {
                return ResourceManager.GetString("CommandRevertConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the changed application settings to their previous values.
        /// </summary>
        public static string CommandRevertConfigTooltip {
            get {
                return ResourceManager.GetString("CommandRevertConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CommandSave {
            get {
                return ResourceManager.GetString("CommandSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all modifications to data.
        /// </summary>
        public static string CommandSaveTooltip {
            get {
                return ResourceManager.GetString("CommandSaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string CommandStatistics {
            get {
                return ResourceManager.GetString("CommandStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string CommandSubmission {
            get {
                return ResourceManager.GetString("CommandSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, view and modify submission information.
        /// </summary>
        public static string CommandSubmissionTooltip {
            get {
                return ResourceManager.GetString("CommandSubmissionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string CommandTable {
            get {
                return ResourceManager.GetString("CommandTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string CommandTag {
            get {
                return ResourceManager.GetString("CommandTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string CommandTitle {
            get {
                return ResourceManager.GetString("CommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter options.
        /// </summary>
        public static string CommandTitleFilter {
            get {
                return ResourceManager.GetString("CommandTitleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View or hide the title filter options.
        /// </summary>
        public static string CommandTitleFilterTooltip {
            get {
                return ResourceManager.GetString("CommandTitleFilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage existing titles, create new titles, etc..
        /// </summary>
        public static string CommandTitleTooltip {
            get {
                return ResourceManager.GetString("CommandTitleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string CommandTool {
            get {
                return ResourceManager.GetString("CommandTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string CommandToolConvert {
            get {
                return ResourceManager.GetString("CommandToolConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string CommandToolExport {
            get {
                return ResourceManager.GetString("CommandToolExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string CommandToolMeta {
            get {
                return ResourceManager.GetString("CommandToolMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Orphans.
        /// </summary>
        public static string CommandToolOrphan {
            get {
                return ResourceManager.GetString("CommandToolOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble.
        /// </summary>
        public static string CommandToolScramble {
            get {
                return ResourceManager.GetString("CommandToolScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string CommandToolSearch {
            get {
                return ResourceManager.GetString("CommandToolSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title list.
        /// </summary>
        public static string CommandToolTitleList {
            get {
                return ResourceManager.GetString("CommandToolTitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string CommandUserNote {
            get {
                return ResourceManager.GetString("CommandUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Grid.
        /// </summary>
        public static string ConfigDataGrid {
            get {
                return ResourceManager.GetString("ConfigDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row alternation.
        /// </summary>
        public static string ConfigDataGridRowAlternation {
            get {
                return ResourceManager.GetString("ConfigDataGridRowAlternation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row height.
        /// </summary>
        public static string ConfigDataGridRowHeight {
            get {
                return ResourceManager.GetString("ConfigDataGridRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will add a new title record. If any title filters are in effect, they will be removed so that the new title displays in the list. 
        ///
        ///Do you want to continue?.
        /// </summary>
        public static string ConfirmationAddTitle {
            get {
                return ResourceManager.GetString("ConfirmationAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. All eligible version files renamed..
        /// </summary>
        public static string ConfirmationAllVersionFilesRenamed {
            get {
                return ResourceManager.GetString("ConfirmationAllVersionFilesRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title extracted from the latest version is:
        ///
        ///{0}
        ///
        ///Do you want to set the title to this value?.
        /// </summary>
        public static string ConfirmationApplyExtractedTitleFormat {
            get {
                return ResourceManager.GetString("ConfirmationApplyExtractedTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a document (NOT READY).
        /// </summary>
        public static string ConfirmationCreateSubmissionDocument {
            get {
                return ResourceManager.GetString("ConfirmationCreateSubmissionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this author?.
        /// </summary>
        public static string ConfirmationDeleteAuthor {
            get {
                return ResourceManager.GetString("ConfirmationDeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will remove the selected credential and remove its association with any publishers that are using it. Do you want to continue?.
        /// </summary>
        public static string ConfirmationDeleteCredential {
            get {
                return ResourceManager.GetString("ConfirmationDeleteCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the selected file from disk. Do you want to continue?.
        /// </summary>
        public static string ConfirmationDeleteFile {
            get {
                return ResourceManager.GetString("ConfirmationDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this link?.
        /// </summary>
        public static string ConfirmationDeleteLink {
            get {
                return ResourceManager.GetString("ConfirmationDeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this note?.
        /// </summary>
        public static string ConfirmationDeleteNote {
            get {
                return ResourceManager.GetString("ConfirmationDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to delete this publisher. Do you want to continue?.
        /// </summary>
        public static string ConfirmationDeletePublisher {
            get {
                return ResourceManager.GetString("ConfirmationDeletePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to delete this submission. This will remove the submission record and all associated records such as submission documents and messages. It does not remove any documents from disk. Do you want to continue?.
        /// </summary>
        public static string ConfirmationDeleteSubmission {
            get {
                return ResourceManager.GetString("ConfirmationDeleteSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to delete this submission document. This only deletes the entry in the database, not the associated document. Do you want to continue?.
        /// </summary>
        public static string ConfirmationDeleteSubmissionDocument {
            get {
                return ResourceManager.GetString("ConfirmationDeleteSubmissionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this tag?.
        /// </summary>
        public static string ConfirmationDeleteTag {
            get {
                return ResourceManager.GetString("ConfirmationDeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to delete this title. This only deletes the entry in the database, not any associated documents (Word, PDF, etc.) Do you  want to continue?.
        /// </summary>
        public static string ConfirmationDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmationDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this note?.
        /// </summary>
        public static string ConfirmationDeleteUserNote {
            get {
                return ResourceManager.GetString("ConfirmationDeleteUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to remove this message. If this message is a direct link to the Outlook message store, the message remains there unless you delete it directly. Do you want to continue?.
        /// </summary>
        public static string ConfirmationRemoveSubmissionMessage {
            get {
                return ResourceManager.GetString("ConfirmationRemoveSubmissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this submission period for this publisher?.
        /// </summary>
        public static string ConfirmationRemoveSubmissionPeriod {
            get {
                return ResourceManager.GetString("ConfirmationRemoveSubmissionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove title from this submission?.
        /// </summary>
        public static string ConfirmationRemoveTitleFromSubmission {
            get {
                return ResourceManager.GetString("ConfirmationRemoveTitleFromSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this record of publication for this title?.
        /// </summary>
        public static string ConfirmationRemoveTitlePublished {
            get {
                return ResourceManager.GetString("ConfirmationRemoveTitlePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will remove the selected version from this title. It does not delete the file on disk. Do you want to continue?.
        /// </summary>
        public static string ConfirmationRemoveTitleVersion {
            get {
                return ResourceManager.GetString("ConfirmationRemoveTitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title list has been copied to the clipboard.
        /// </summary>
        public static string ConfirmationTitlesCopiedToClipboard {
            get {
                return ResourceManager.GetString("ConfirmationTitlesCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title has been previously submitted to the same publisher. Do you want to continue and submit it to the same publisher again?.
        /// </summary>
        public static string ConfirmationTitleSubmittedPreviouslyToPublisher {
            get {
                return ResourceManager.GetString("ConfirmationTitleSubmittedPreviouslyToPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name.
        /// </summary>
        public static string FilterPromptAuthor {
            get {
                return ResourceManager.GetString("FilterPromptAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential name.
        /// </summary>
        public static string FilterPromptCredential {
            get {
                return ResourceManager.GetString("FilterPromptCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link name or note.
        /// </summary>
        public static string FilterPromptLink {
            get {
                return ResourceManager.GetString("FilterPromptLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher name.
        /// </summary>
        public static string FilterPromptPublisher {
            get {
                return ResourceManager.GetString("FilterPromptPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher or response type.
        /// </summary>
        public static string FilterPromptSubmission {
            get {
                return ResourceManager.GetString("FilterPromptSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string FilterPromptTable {
            get {
                return ResourceManager.GetString("FilterPromptTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name.
        /// </summary>
        public static string FilterPromptTag {
            get {
                return ResourceManager.GetString("FilterPromptTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FilterPromptTitle {
            get {
                return ResourceManager.GetString("FilterPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note title.
        /// </summary>
        public static string FilterPromptUserNote {
            get {
                return ResourceManager.GetString("FilterPromptUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a submission to {0}?.
        /// </summary>
        public static string FormatStringCreateSubmission {
            get {
                return ResourceManager.GetString("FormatStringCreateSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: You already have at least one submission to this publisher that has not yet received a response. Do you want to continue and create another submission?.
        /// </summary>
        public static string FormatStringCreateSubmissionOpen {
            get {
                return ResourceManager.GetString("FormatStringCreateSubmissionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist.
        ///
        ///{0}
        ///
        ///Please make sure that {1} is set correctly in configuration settings. File specifications are relative to this setting..
        /// </summary>
        public static string FormatStringFileNotFound {
            get {
                return ResourceManager.GetString("FormatStringFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder contains exported versions of each title tracked by {0}.
        ///Files are named according to the date they were first written, title, version, and language.
        ///
        ///Usually, the individual files are kept in different sub directories; this directory has all files in one place.
        ///
        ///Last exported: {1}.
        /// </summary>
        public static string FormatTextExport {
            get {
                return ResourceManager.GetString("FormatTextExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string HeaderData {
            get {
                return ResourceManager.GetString("HeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string HeaderDates {
            get {
                return ResourceManager.GetString("HeaderDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string HeaderDocuments {
            get {
                return ResourceManager.GetString("HeaderDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string HeaderMessages {
            get {
                return ResourceManager.GetString("HeaderMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string HeaderPreview {
            get {
                return ResourceManager.GetString("HeaderPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string HeaderPublished {
            get {
                return ResourceManager.GetString("HeaderPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string HeaderSettingsDateFormat {
            get {
                return ResourceManager.GetString("HeaderSettingsDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string HeaderSettingsFolder {
            get {
                return ResourceManager.GetString("HeaderSettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string HeaderSettingsSectionColor {
            get {
                return ResourceManager.GetString("HeaderSettingsSectionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string HeaderSettingsSectionFolder {
            get {
                return ResourceManager.GetString("HeaderSettingsSectionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string HeaderSettingsSectionGeneral {
            get {
                return ResourceManager.GetString("HeaderSettingsSectionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission.
        /// </summary>
        public static string HeaderSettingsSectionSubmission {
            get {
                return ResourceManager.GetString("HeaderSettingsSectionSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string HeaderSubmissions {
            get {
                return ResourceManager.GetString("HeaderSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string HeaderTitles {
            get {
                return ResourceManager.GetString("HeaderTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation converts all .doc files in the specified folder to Open Xml (.docx ) files. If the converted file belongs to a title version, the version record will be updated to reflect the change. If a corresponding .docx file exists in the folder (for example, Report.doc and Report.docx), the .docx file will be overwritten. After the conversion, the .doc file will be sent to the recycle bin..
        /// </summary>
        public static string HeaderToolOperationConvert {
            get {
                return ResourceManager.GetString("HeaderToolOperationConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} eligible files, {1} converted.
        /// </summary>
        public static string HeaderToolOperationConvertFoundFormat {
            get {
                return ResourceManager.GetString("HeaderToolOperationConvertFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation exports all versions of each title to the specifed folder. Each file will be named in accordance with the date it was written, its title, language and version. Only files that have changed or are not present in the export directory will be exported. Extra files in the export directory will be deleted. Files are exported to: {0}.
        /// </summary>
        public static string HeaderToolOperationExport {
            get {
                return ResourceManager.GetString("HeaderToolOperationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission documents (not found) - {0}.
        /// </summary>
        public static string HeaderToolOperationMetaSubmissionNotFoundFormat {
            get {
                return ResourceManager.GetString("HeaderToolOperationMetaSubmissionNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission documents (updated) - {0}.
        /// </summary>
        public static string HeaderToolOperationMetaSubmissionUpdatedFormat {
            get {
                return ResourceManager.GetString("HeaderToolOperationMetaSubmissionUpdatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title documents (not found) - {0}.
        /// </summary>
        public static string HeaderToolOperationMetaTitleNotFoundFormat {
            get {
                return ResourceManager.GetString("HeaderToolOperationMetaTitleNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title documents (updated) - {0}.
        /// </summary>
        public static string HeaderToolOperationMetaTitleUpdatedFormat {
            get {
                return ResourceManager.GetString("HeaderToolOperationMetaTitleUpdatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation first compacts the database file, and then verfies that all files associated with title versions and submission documents are present on disk and updates meta data that is stored in the database regarding each file, such as last updated date/time and word count..
        /// </summary>
        public static string HeaderToolOperationMetaUpdate {
            get {
                return ResourceManager.GetString("HeaderToolOperationMetaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation searches all files beneath the title root directory to find those files that are not associated with a title entry..
        /// </summary>
        public static string HeaderToolOperationOrphan {
            get {
                return ResourceManager.GetString("HeaderToolOperationOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files (not associated with a title entry) - {0}.
        /// </summary>
        public static string HeaderToolOperationOrphanNotFoundFormat {
            get {
                return ResourceManager.GetString("HeaderToolOperationOrphanNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation enables to scramble lines of text, and optionaly the words within the lines. Paste text to begin..
        /// </summary>
        public static string HeaderToolOperationScramble {
            get {
                return ResourceManager.GetString("HeaderToolOperationScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation searches all files beneath the title root directory to find all files that contain the specified search term..
        /// </summary>
        public static string HeaderToolOperationSearch {
            get {
                return ResourceManager.GetString("HeaderToolOperationSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results - {0}.
        /// </summary>
        public static string HeaderToolOperationSearchFoundFormat {
            get {
                return ResourceManager.GetString("HeaderToolOperationSearchFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation creates a text file that has a list of all titles and their corresponding versions. The text file is placed in the TitleRoot folder..
        /// </summary>
        public static string HeaderToolOperationTitleList {
            get {
                return ResourceManager.GetString("HeaderToolOperationTitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These properties are the same ones you can change from within Microsoft Word; they are saved within the document itself.
        ///
        ///When you save properties here however, the document&apos;s file  modification date is not set to the current date / time as it is when you make the changes from within Word. Instead,  the modification date is incremented by 15 seconds from its original..
        /// </summary>
        public static string HeaderVersionProperties {
            get {
                return ResourceManager.GetString("HeaderVersionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The properties for this version cannot be displayed. Only Open Xml documents are supported..
        /// </summary>
        public static string HeaderVersionPropertiesNotOpenXml {
            get {
                return ResourceManager.GetString("HeaderVersionPropertiesNotOpenXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        public static string HeaderVersions {
            get {
                return ResourceManager.GetString("HeaderVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory that will hold the database files.
        /// </summary>
        public static string InstallationCaption {
            get {
                return ResourceManager.GetString("InstallationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author cannot be deleted. He or she is participating in {0} titles. .
        /// </summary>
        public static string InvalidOpCannotDeleteAuthor {
            get {
                return ResourceManager.GetString("InvalidOpCannotDeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This publisher cannot be deleted. It is participating in {0} submissions. .
        /// </summary>
        public static string InvalidOpCannotDeletePublisher {
            get {
                return ResourceManager.GetString("InvalidOpCannotDeletePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag cannot be deleted. It is being used by {0} titles. .
        /// </summary>
        public static string InvalidOpCannotDeleteTag {
            get {
                return ResourceManager.GetString("InvalidOpCannotDeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title cannot be deleted. It is participating in {0} submissions. .
        /// </summary>
        public static string InvalidOpCannotDeleteTitle {
            get {
                return ResourceManager.GetString("InvalidOpCannotDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is not supported.
        /// </summary>
        public static string InvalidOpCommandNotSupported {
            get {
                return ResourceManager.GetString("InvalidOpCommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exist.
        /// </summary>
        public static string InvalidOpDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("InvalidOpDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document type is obsolete and is no longer supported.
        /// </summary>
        public static string InvalidOpDocumentTypeNotSupported {
            get {
                return ResourceManager.GetString("InvalidOpDocumentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for the export operation hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string InvalidOpExportFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpExportFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Outlook folder  from which to select submission messages hasn&apos;t been set. Fix the configuration and try again..
        /// </summary>
        public static string InvalidOpMapiFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpMapiFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open. There is no document associated with this entry..
        /// </summary>
        public static string InvalidOpNoDocumentId {
            get {
                return ResourceManager.GetString("InvalidOpNoDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough text to scramble. Paste some more text and try again..
        /// </summary>
        public static string InvalidOpNotEnoughTextToScramble {
            get {
                return ResourceManager.GetString("InvalidOpNotEnoughTextToScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the version files for this title have already been renamed..
        /// </summary>
        public static string InvalidOpRenameAllCandidatesAlreadyRenamed {
            get {
                return ResourceManager.GetString("InvalidOpRenameAllCandidatesAlreadyRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions exist to rename.
        /// </summary>
        public static string InvalidOpRenameCandidateListEmpty {
            get {
                return ResourceManager.GetString("InvalidOpRenameCandidateListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be completed because the file for version {0}
        ///
        ///{1} 
        ///
        ///does not exist. Correct this by selecting the correct file and then try again..
        /// </summary>
        public static string InvalidOpRenameFileDoesNotExistFormat {
            get {
                return ResourceManager.GetString("InvalidOpRenameFileDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the version files does not exist.
        /// </summary>
        public static string InvalidOpRenameFilesMissing {
            get {
                return ResourceManager.GetString("InvalidOpRenameFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for submission documents hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string InvalidOpSubmissionDocumentFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpSubmissionDocumentFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified title record does not exist.
        /// </summary>
        public static string InvalidOpTitleDoesNotExist {
            get {
                return ResourceManager.GetString("InvalidOpTitleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output folder for the title list operation does not exist..
        /// </summary>
        public static string InvalidOpTitleListOutputFolder {
            get {
                return ResourceManager.GetString("InvalidOpTitleListOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title root folder hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string InvalidOpTitleRootFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpTitleRootFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot exit at this time. Background tasks are still running..
        /// </summary>
        public static string NotificationCannotExitTasksAreRunning {
            get {
                return ResourceManager.GetString("NotificationCannotExitTasksAreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission created.
        /// </summary>
        public static string ResultSubmissionCreated {
            get {
                return ResourceManager.GetString("ResultSubmissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string TextNone {
            get {
                return ResourceManager.GetString("TextNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record.
        /// </summary>
        public static string TextRecord {
            get {
                return ResourceManager.GetString("TextRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        public static string TextRecords {
            get {
                return ResourceManager.GetString("TextRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string TextResponse {
            get {
                return ResourceManager.GetString("TextResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string TextSubmitted {
            get {
                return ResourceManager.GetString("TextSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written.
        /// </summary>
        public static string TextWritten {
            get {
                return ResourceManager.GetString("TextWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display drop down colors in alphabetical order.
        /// </summary>
        public static string TooltipColorAlpha {
            get {
                return ResourceManager.GetString("TooltipColorAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display drop down colors in order of hue, saturation and brightness.
        /// </summary>
        public static string TooltipColorHSB {
            get {
                return ResourceManager.GetString("TooltipColorHSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all colors to their default values.
        /// </summary>
        public static string TooltipColorReset {
            get {
                return ResourceManager.GetString("TooltipColorReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date this publisher was added to the database.
        /// </summary>
        public static string TooltipPublisherAdded {
            get {
                return ResourceManager.GetString("TooltipPublisherAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher is currently in one of its submission periods.
        /// </summary>
        public static string TooltipPublisherInPeriod {
            get {
                return ResourceManager.GetString("TooltipPublisherInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date that the last submission was created for this publisher.
        /// </summary>
        public static string TooltipPublisherLastSubmission {
            get {
                return ResourceManager.GetString("TooltipPublisherLastSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher is a paying market.
        /// </summary>
        public static string TooltipPublisherPay {
            get {
                return ResourceManager.GetString("TooltipPublisherPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission count - the total number of times a submission has been made to this publisher.
        /// </summary>
        public static string TooltipPublisherSubmissionCount {
            get {
                return ResourceManager.GetString("TooltipPublisherSubmissionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission period count - the total number of submission periods that have been assigned to this publisher.
        /// </summary>
        public static string TooltipPublisherSubmissionPeriodCount {
            get {
                return ResourceManager.GetString("TooltipPublisherSubmissionPeriodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current submission count - the number of submissions that are still open for this title.
        /// </summary>
        public static string TooltipTitleCurrentSubmissionCount {
            get {
                return ResourceManager.GetString("TooltipTitleCurrentSubmissionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published count - the number of times this title has been published..
        /// </summary>
        public static string TooltipTitlePublishedCount {
            get {
                return ResourceManager.GetString("TooltipTitlePublishedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission count - the total number of times this title has been submitted.
        /// </summary>
        public static string TooltipTitleSubmissionCount {
            get {
                return ResourceManager.GetString("TooltipTitleSubmissionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag count - the number of tags assigned to this title.
        /// </summary>
        public static string TooltipTitleTagCount {
            get {
                return ResourceManager.GetString("TooltipTitleTagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updated date for the latest version of this title.
        /// </summary>
        public static string TooltipTitleUpdated {
            get {
                return ResourceManager.GetString("TooltipTitleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version count - the number of versions that this title has.
        /// </summary>
        public static string TooltipTitleVersionCount {
            get {
                return ResourceManager.GetString("TooltipTitleVersionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word count - the number of words in the latest version of this title.
        /// </summary>
        public static string TooltipTitleWordCount {
            get {
                return ResourceManager.GetString("TooltipTitleWordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An integer value is required.
        /// </summary>
        public static string ValidationOperationIntegerNeeded {
            get {
                return ResourceManager.GetString("ValidationOperationIntegerNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a publisher for this published record.
        /// </summary>
        public static string WindowTitleSelectPublisherForPublished {
            get {
                return ResourceManager.GetString("WindowTitleSelectPublisherForPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a publisher.
        /// </summary>
        public static string WindowTitleSelectPublisherGeneric {
            get {
                return ResourceManager.GetString("WindowTitleSelectPublisherGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename title version files.
        /// </summary>
        public static string WindowTitleVersionRename {
            get {
                return ResourceManager.GetString("WindowTitleVersionRename", resourceCulture);
            }
        }
    }
}
