INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (1, 'Abyss and Apex', 'www.abyssapexzine.com/', 'Possible publisher', 0, '2010-06-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (2, 'Cabinet des Fées', 'www.cabinetdesfees.com', 'Possible publisher', 0, '2010-06-30 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (3, 'Duotrope', 'www.duotrope.com', 'Resource', 9, '2010-07-25 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (4, 'U.S. Poets in Mexico', 'www.uspoetsinmexico.org', 'Maybe get a scholarship', 0, '2010-07-29 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (7, '42 Opus', '42opus.com', '', 0, '2010-08-11 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (8, 'Swan Isle Press', 'www.swanislepress.com', 'Possible publisher', 0, '2010-08-15 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (9, 'The Cafe Review', 'www.thecafereview.com', 'Home of Poet''s Cafe', 0, '2010-09-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (10, 'Waterstone Review', 'www.waterstonereview.com', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (11, 'Tinhouse', 'www.tinhouse.com', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (12, 'Lake Effect', 'www.pserie.psu.edu/academic/hss/lakeeffect/about/Submissions.html', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (13, 'Green Mountain Review', 'greenmountainsreview.jsc.vsc.edu', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (14, 'Alaska Quarterly', 'www.uaa.alaska.edu/aqr', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (15, 'Front Range', 'www.frontrangemt.org', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (16, 'Burnside Review', 'www.burnsidereview.org', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (18, 'New York Quarterly', 'www.newyorkquarterly.com/submit.html', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (19, 'The Sun', 'www.thesunmagazine.org/about/submission_guidelines/writing', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (20, 'Georgia Review', 'www.uga.edu/garev', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (21, 'Poetry Foundation', 'www.poetryfoundation.org/poetrymagazine/submissions.html', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (22, 'Virginia Quarterly', 'www.vqronline.org', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (23, 'Zoetrope', 'www.all-story.com', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (24, 'Ploughshares', 'www.pshares.org', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (25, 'Missouri Review', 'www.missourireview.org', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (26, 'Indiana Review', 'www.indiana.edu/~inreview', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (27, 'Black Warrior Review', 'bwr.ua.edu/', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (28, 'New England Review', 'cat.middlebury.edu/~nereview', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (29, 'The Colorado Review', 'coloradoreview.colostate.edu/colorado-review/', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (30, 'Conjunctions', 'www.conjunctions.com', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (31, 'American Poetry Review', 'www.aprweb.org', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (32, 'ZYZZYVA', 'www.zyzzyva.org', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (33, 'Hudson Review', 'www.hudsonreview.com', 'From Lana: Print', 0, '2010-10-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (34, 'New Pages', 'www.newpages.com/', 'Resource', 0, '2013-04-02 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (35, 'Poets & Writers (Magazines)', 'www.pw.org/literary_magazines', 'Resource', 11, '2013-04-02 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (36, 'Buffalo Poetry List (Welcome)', 'epc.buffalo.edu/poetics/welcome.html', NULL, 0, '2013-04-26 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (37, 'Buffalo Poetry List (Archives)', 'listserv.buffalo.edu/cgi-bin/wa\x3fA0=POETICS', NULL, 0, '2013-04-26 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (38, 'Sara Uribe (EDGE), translated by Toshiya Kamei', 'fourwayreview.com/edge-by-sara-uribe-translated-by-toshiya-kamei/', 'Poems I Like', 0, '2013-05-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (39, 'Sara Uribe (JANUARY), translated by Toshiya Kamei', 'fourwayreview.com/january-by-sara-uribe-translated-by-toshiya-kamei/', 'Poems I Like', 0, '2013-05-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (40, 'Sara Uribe (TICKET), translated by Toshiya Kamei', 'und.edu/orgs/floodwall/_files/docs/uribeandkamei-poetryfall2012.cfm', 'Poems I Like', 0, '2013-05-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (41, 'Sara Uribe (GHOST), translated by Toshiya Kamei', 'www.poydrasreview.com/Read/files/blogContents.php\x3fid=97144297913448241', 'Poems I Like', 0, '2013-05-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (42, 'Maria Hummel - The Angels', 'fourwayreview.com/the-angels-by-maria-hummel/', 'Poems I Like', 0, '2013-05-01 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (43, 'Inspired Quill', 'www.inspired-quill.com/', 'Possible publisher', 0, '2013-06-03 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (44, 'Write Out Loud', 'www.writeoutloud.net', 'Resource', 0, '2013-06-04 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (45, 'Writers Relief', 'www.writersrelief.com', 'Resource', 0, '2013-06-04 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (46, 'Writers Database', 'www.writersdb.com', 'Resource', 0, '2013-06-10 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (47, 'Poetry Publishers w/ electronic submissions', 'andromeda.rutgers.edu/~lcrew/pbonline.html', 'Resource', 0, '2013-06-16 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (48, 'The Review Review', 'www.thereviewreview.net', 'Resource', 0, '2013-07-08 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (49, 'List of Literary Magazines', 'en.wikipedia.org/wiki/List_of_literary_magazines', 'Resource', 0, '2013-09-09 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (50, 'Tell It Slant', 'https://www.tellitslant.com', 'Submission System', 8, '2013-09-16 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (51, 'Submittable Manager', 'https://manager.submittable.com/login', 'Submission System', 1, '2013-09-17 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (52, 'Dana Gioia', 'www.danagioia.net/', 'Essays', 0, '2013-12-11 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (53, 'Michael Alexander Chaney', 'michaelalexanderchaney.com', 'Resource', 0, '2013-12-13 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (54, 'Pif Magazine', 'www.pifmagazine.com', 'Possible publisher', 0, '2014-02-18 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (55, 'World City Stories', 'worldcitystories.com', 'Possible publisher', 0, '2014-02-20 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (56, 'Build Book Buzz', 'buildbookbuzz.com', 'Resource', 0, '2014-03-23 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (57, 'Libros Libertad', 'www.libroslibertad.ca', 'Possible publisher', 0, '2014-03-23 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (58, 'Preditors & Editors', 'pred-ed.com', 'Resource', 0, '2014-06-22 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (59, 'Victor David - Interview @ Sugared Water', 'sugaredwatermagazine.wordpress.com/2014/08/22/poetry-sandiego/', 'Interview', 0, '2014-10-09 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (60, 'Victor David - Interview @ Kevs', 'kevs-domain.net/2014/06/28/presenting-the-fascinating-victor-d-sandiego/', 'Interview', 0, '2014-10-09 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (61, 'Phillippe Diederich', 'roadtoabestseller.com', 'Stuff I Like', 0, '2014-10-14 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (62, 'Poetry Markets', 'poetrymarkets.com', 'Resource', 0, '2015-05-26 00:00:00');
INSERT INTO "link" ("id", "name", "url", "notes", "credentialid", "added") VALUES (63, 'Writing Career', 'writingcareer.com', 'Resource', 0, '2016-11-22 00:00:00');