INSERT INTO "config"  VALUES ('AutoSwitchToSubmission', 'Create if necessary and switch to the submission tab when creating a submission', 'bool', '1', 1);
INSERT INTO "config"  VALUES ('ColorPeriodPublisher', 'Color used to show publishers in submission period', 'color', '#FF008000', 1);
INSERT INTO "config"  VALUES ('ColorPublishedTitle', 'Color used to show published titles', 'color', '#FF00FF00', 1);
INSERT INTO "config"  VALUES ('ColorSubmittedTitle', 'Color used to show submitted titles', 'color', '#FFFF0000', 1);
INSERT INTO "config"  VALUES ('DateFormat', 'The format string used to display dates', 'string', 'MMM dd, yyyy', 1);
INSERT INTO "config"  VALUES ('DefaultBrowser', 'The browser to use when opening a link', 'browser', '', 0);
INSERT INTO "config"  VALUES ('FolderExport', 'Folder to place documents for the export operation', 'path', NULL, 1);
INSERT INTO "config"  VALUES ('FolderMapi', 'The Outlook folder that contains submission messages', 'mapi', NULL, 1);
INSERT INTO "config"  VALUES ('FolderSubmissionDocument', 'The folder for submission documents', 'path', NULL, 1);
INSERT INTO "config"  VALUES ('FolderSubmissionMessageAttachment', 'Folder where submission message attachments are saved', 'path', NULL, 1);
INSERT INTO "config"  VALUES ('FolderTitle', 'The default folder for selecting a title version document', 'path', NULL, 1);
INSERT INTO "config"  VALUES ('FolderTitleRoot', 'Root folder of title documents', 'path', NULL, 1);
INSERT INTO "config"  VALUES ('LeftColumnPublisher', 'The left column width for publisher view', 'int', '684', 0);
INSERT INTO "config"  VALUES ('LeftColumnSubmission', 'The left column width for submission view', 'int', '684', 0);
INSERT INTO "config"  VALUES ('LeftColumnTable', 'The left column width for table view', 'int', '684', 0);
INSERT INTO "config"  VALUES ('LeftColumnTitle', 'The left column width for title view', 'int', '684', 0);
INSERT INTO "config"  VALUES ('MainWindowHeight', 'The height of the main window', 'int', '840', 0);
INSERT INTO "config"  VALUES ('MainWindowState', 'The state of the main window. 0=normal, 1=min,2-max', 'int', '0', 0);
INSERT INTO "config"  VALUES ('MainWindowWidth', 'The width of the main window', 'int', '1420', 0);
INSERT INTO "config"  VALUES ('OpsConfig', 'Toolbar, status bar, etc. A bit-mapped value', 'int', '348807', 0);
INSERT INTO "config"  VALUES ('OpsStartup', 'The startup options. A bit-mapped value.', 'int', '577', 0);
INSERT INTO "config"  VALUES ('OpsToolbar', 'Options to display toolbar buttons. A bit-mapped value', 'int', '5114', 0);
INSERT INTO "config"  VALUES ('PublisherFilter', 'The publisher filter object', 'object', NULL, 0);
INSERT INTO "config"  VALUES ('SubDocumentAuthor', 'The author name placed in a new submission document', 'string', NULL, 1);
INSERT INTO "config"  VALUES ('SubDocumentCompany', 'The company name inserted into a new submission document', 'string', NULL, 1);
INSERT INTO "config"  VALUES ('SubDocumentFooter', 'The footer template for creating a new document', 'string', 'Submissions to [publisher] - [author] - [month], [year]', 1);
INSERT INTO "config"  VALUES ('SubDocumentFooterPages', 'Add page # in the footer when creating a submission document', 'bool', '1', 1);
INSERT INTO "config"  VALUES ('SubDocumentHeader', 'The header template for creating a new document', 'string', NULL, 1);
INSERT INTO "config"  VALUES ('SubDocumentHeaderPages', 'Add page # in the header when creating a submission document', 'bool', '1', 1);
INSERT INTO "config"  VALUES ('SubDocumentText', 'Text inserted into a new submission document', 'mstring', NULL, 1);
INSERT INTO "config"  VALUES ('SyncDocumentInternalDates', 'During a meta-data update operation, updates document internal dates (created, modified) to be consistent with the title written date and the file system modified date, respectively. This only works on Open Xml documents.', 'bool', '0', 1);
INSERT INTO "config"  VALUES ('TitleFilter', 'The title filter object', 'object', NULL, 0);
