INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (0, 'Unknown', NULL, 100, 0);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (1, 'Word Document (OpenXml)', '.docx;.dotm', 1, 1);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (2, 'Word Document (Old)', '.doc;.rtf', 2, 1);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (3, 'Pdf Document', '.pdf', 3, 1);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (4, 'Text Document', '.txt', 4, 1);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (5, 'Outlook Message', '.msg', 7, 1);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (6, 'Outlook Message (Direct Reference)', NULL, 100, 0);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (7, 'Outlook Folder (Direct Reference)', NULL, 100, 0);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (8, 'Audio', '.mp3', 6, 1);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (9, 'Html', '.html;.htm', 5, 1);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (10, 'Images', '.jpg;.jpeg;.png', 7, 1);
INSERT INTO "documenttype" ("id", "name", "extensions", "ordering", "supported") VALUES (11, 'Executable', '.exe', 9, 1);
