//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Confirm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Confirm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Confirm", typeof(Confirm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will add a new alert record. If any filters are in effect, they will be removed so that the new alert displays in the list..
        /// </summary>
        public static string AddAlert {
            get {
                return ResourceManager.GetString("AddAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will add a new author record. If any filters are in effect, they will be removed so that the new author displays in the list..
        /// </summary>
        public static string AddAuthor {
            get {
                return ResourceManager.GetString("AddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation excludes the directory of the selected file from further orphan search.
        /// </summary>
        public static string AddOrphanDirectoryExclusion {
            get {
                return ResourceManager.GetString("AddOrphanDirectoryExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation excludes the selected file from further orphan search.
        /// </summary>
        public static string AddOrphanFileExclusion {
            get {
                return ResourceManager.GetString("AddOrphanFileExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation excludes all files of the selected file type from further orphan search.
        /// </summary>
        public static string AddOrphanFileTypeExclusion {
            get {
                return ResourceManager.GetString("AddOrphanFileTypeExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will add a new publisher record. If any publisher filters are in effect, they will be removed so that the new publisher displays in the list..
        /// </summary>
        public static string AddPublisher {
            get {
                return ResourceManager.GetString("AddPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation adds a submission period that runs from January 1 - December 31, i.e. all year. Once added, you can change the range of the submission period if needed..
        /// </summary>
        public static string AddSubmissionPeriod {
            get {
                return ResourceManager.GetString("AddSubmissionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will add a new title record. If any title filters are in effect, they will be removed so that the new title displays in the list..
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. All eligible version files renamed..
        /// </summary>
        public static string AllVersionFilesRenamed {
            get {
                return ResourceManager.GetString("AllVersionFilesRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation clears the published date for this item. You can set the date again at any time..
        /// </summary>
        public static string ClearPublishedDate {
            get {
                return ResourceManager.GetString("ClearPublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will clear the quick flag from all titles. Do you want to continue?.
        /// </summary>
        public static string ClearTitleFlags {
            get {
                return ResourceManager.GetString("ClearTitleFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a document (NOT READY).
        /// </summary>
        public static string CreateSubmissionDocument {
            get {
                return ResourceManager.GetString("CreateSubmissionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a submission to {0}?.
        /// </summary>
        public static string CreateSubmissionFormat {
            get {
                return ResourceManager.GetString("CreateSubmissionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: You already have at least one submission to this publisher that has not yet received a response. Do you want to continue and create another submission?.
        /// </summary>
        public static string CreateSubmissionOpenFormat {
            get {
                return ResourceManager.GetString("CreateSubmissionOpenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will create a title entry and use the selected file as the first version that is associated with the title. The written date for the title will be set to the last modified date of the file..
        /// </summary>
        public static string CreateTitleFromOrphan {
            get {
                return ResourceManager.GetString("CreateTitleFromOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this alert?.
        /// </summary>
        public static string DeleteAlert {
            get {
                return ResourceManager.GetString("DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this author?.
        /// </summary>
        public static string DeleteAuthor {
            get {
                return ResourceManager.GetString("DeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will remove the selected credential and remove its association with any publishers that are using it. Do you want to continue?.
        /// </summary>
        public static string DeleteCredential {
            get {
                return ResourceManager.GetString("DeleteCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the selected file from disk. Do you want to continue?.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this link?.
        /// </summary>
        public static string DeleteLink {
            get {
                return ResourceManager.GetString("DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to delete this publisher. Do you want to continue?.
        /// </summary>
        public static string DeletePublisher {
            get {
                return ResourceManager.GetString("DeletePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to delete this submission. This will remove the submission record and all associated records such as submission documents and messages. It does not remove any documents from disk. Do you want to continue?.
        /// </summary>
        public static string DeleteSubmission {
            get {
                return ResourceManager.GetString("DeleteSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to delete this submission document. This only deletes the entry in the database, not the associated document. Do you want to continue?.
        /// </summary>
        public static string DeleteSubmissionDocument {
            get {
                return ResourceManager.GetString("DeleteSubmissionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this tag?.
        /// </summary>
        public static string DeleteTag {
            get {
                return ResourceManager.GetString("DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to delete this title. This only deletes the entry in the database, not any associated documents (Word, PDF, etc.) Do you  want to continue?.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this note?.
        /// </summary>
        public static string DeleteUserNote {
            get {
                return ResourceManager.GetString("DeleteUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sets the title of this entry to the value extracted from the latest version: {0}.
        /// </summary>
        public static string ExtractedTitleFormat {
            get {
                return ResourceManager.GetString("ExtractedTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation removes the selected queue. It does not affect any title record themselves..
        /// </summary>
        public static string RemoveQueue {
            get {
                return ResourceManager.GetString("RemoveQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation removes the selected title from the queue. It does not affect the title itself..
        /// </summary>
        public static string RemoveQueueTitle {
            get {
                return ResourceManager.GetString("RemoveQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation removes the related title from this title. It does not affect the related title itself..
        /// </summary>
        public static string RemoveRelatedTitle {
            get {
                return ResourceManager.GetString("RemoveRelatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to remove this message. This does not delete any external files or resources, only the database entry. Do you want to continue?.
        /// </summary>
        public static string RemoveSubmissionMessage {
            get {
                return ResourceManager.GetString("RemoveSubmissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this submission period for this publisher?.
        /// </summary>
        public static string RemoveSubmissionPeriod {
            get {
                return ResourceManager.GetString("RemoveSubmissionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation removes the title from the selected queue. It does not affect the title itself..
        /// </summary>
        public static string RemoveTitleFromQueue {
            get {
                return ResourceManager.GetString("RemoveTitleFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove title from this submission?.
        /// </summary>
        public static string RemoveTitleFromSubmission {
            get {
                return ResourceManager.GetString("RemoveTitleFromSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation removes the record of publication for this title. You can add a new record back at any time..
        /// </summary>
        public static string RemoveTitlePublished {
            get {
                return ResourceManager.GetString("RemoveTitlePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will remove the selected version from this title. It does not delete the file on disk..
        /// </summary>
        public static string RemoveTitleVersion {
            get {
                return ResourceManager.GetString("RemoveTitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation sets the submission period to January 1 - December 31, i.e. all year..
        /// </summary>
        public static string ResetSubmissionPeriod {
            get {
                return ResourceManager.GetString("ResetSubmissionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title list has been copied to the clipboard.
        /// </summary>
        public static string TitlesCopiedToClipboard {
            get {
                return ResourceManager.GetString("TitlesCopiedToClipboard", resourceCulture);
            }
        }
    }
}
