//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string QueueTitleStatus000 {
            get {
                return ResourceManager.GetString("QueueTitleStatus000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string QueueTitleStatus001 {
            get {
                return ResourceManager.GetString("QueueTitleStatus001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string QueueTitleStatus002 {
            get {
                return ResourceManager.GetString("QueueTitleStatus002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not specified).
        /// </summary>
        public static string SubmissionResponse001 {
            get {
                return ResourceManager.GetString("SubmissionResponse001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Thanks.
        /// </summary>
        public static string SubmissionResponse002 {
            get {
                return ResourceManager.GetString("SubmissionResponse002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string SubmissionResponse003 {
            get {
                return ResourceManager.GetString("SubmissionResponse003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Note.
        /// </summary>
        public static string SubmissionResponse004 {
            get {
                return ResourceManager.GetString("SubmissionResponse004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Blast.
        /// </summary>
        public static string SubmissionResponse010 {
            get {
                return ResourceManager.GetString("SubmissionResponse010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flakey.
        /// </summary>
        public static string SubmissionResponse011 {
            get {
                return ResourceManager.GetString("SubmissionResponse011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        public static string SubmissionResponse100 {
            get {
                return ResourceManager.GetString("SubmissionResponse100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string SubmissionResponse255 {
            get {
                return ResourceManager.GetString("SubmissionResponse255", resourceCulture);
            }
        }
    }
}
