//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has already been added to this title. Please choose a different file..
        /// </summary>
        public static string CannotAddVersionFile {
            get {
                return ResourceManager.GetString("CannotAddVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author cannot be deleted. They are participating in {0} titles..
        /// </summary>
        public static string CannotDeleteAuthor {
            get {
                return ResourceManager.GetString("CannotDeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This publisher cannot be deleted. It is participating in {0} submissions..
        /// </summary>
        public static string CannotDeletePublisher {
            get {
                return ResourceManager.GetString("CannotDeletePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag cannot be deleted. It is being used by {0} titles..
        /// </summary>
        public static string CannotDeleteTag {
            get {
                return ResourceManager.GetString("CannotDeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title cannot be deleted. It is participating in {0} submissions..
        /// </summary>
        public static string CannotDeleteTitle {
            get {
                return ResourceManager.GetString("CannotDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message contents can&apos;t be displayed here. This message is a direct reference to the item stored in the Outlook message store. Double click the row to open the message..
        /// </summary>
        public static string CannotDisplayMapi {
            get {
                return ResourceManager.GetString("CannotDisplayMapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exist.
        /// </summary>
        public static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document type is obsolete and is no longer supported.
        /// </summary>
        public static string DocumentTypeNotSupported {
            get {
                return ResourceManager.GetString("DocumentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not available for this operation. Check that it exists and is not in use by another application..
        /// </summary>
        public static string FileNotAvailable {
            get {
                return ResourceManager.GetString("FileNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} does not exist. Please make sure that {1} is set correctly in configuration settings. File specifications are relative to this setting..
        /// </summary>
        public static string FileNotFoundFormat {
            get {
                return ResourceManager.GetString("FileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open. There is no document associated with this entry..
        /// </summary>
        public static string NoDocumentId {
            get {
                return ResourceManager.GetString("NoDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search scope specified.
        /// </summary>
        public static string NoSearchScope {
            get {
                return ResourceManager.GetString("NoSearchScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for this operation hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string OutputFolderNotSet {
            get {
                return ResourceManager.GetString("OutputFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Preview Not Supported.
        /// </summary>
        public static string PreviewNotSupported {
            get {
                return ResourceManager.GetString("PreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the version files for this title have already been renamed..
        /// </summary>
        public static string RenameAllCandidatesAlreadyRenamed {
            get {
                return ResourceManager.GetString("RenameAllCandidatesAlreadyRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions exist to rename.
        /// </summary>
        public static string RenameCandidateListEmpty {
            get {
                return ResourceManager.GetString("RenameCandidateListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the proposed new file names already exists.
        /// </summary>
        public static string RenameFilesExist {
            get {
                return ResourceManager.GetString("RenameFilesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the version files does not exist.
        /// </summary>
        public static string RenameFilesMissing {
            get {
                return ResourceManager.GetString("RenameFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for submission documents hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string SubmissionDocumentFolderNotSet {
            get {
                return ResourceManager.GetString("SubmissionDocumentFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for submission messages has not been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string SubmissionMessageFolderNotSet {
            get {
                return ResourceManager.GetString("SubmissionMessageFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external text viewer application has not been set. Fix the configuration setting and try again..
        /// </summary>
        public static string TextViewerNotSet {
            get {
                return ResourceManager.GetString("TextViewerNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified title record does not exist.
        /// </summary>
        public static string TitleDoesNotExist {
            get {
                return ResourceManager.GetString("TitleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title root folder hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string TitleRootFolderNotSet {
            get {
                return ResourceManager.GetString("TitleRootFolderNotSet", resourceCulture);
            }
        }
    }
}
