//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Header {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Header() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Header", typeof(Header).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string DefaultShort {
            get {
                return ResourceManager.GetString("DefaultShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string EnabledShort {
            get {
                return ResourceManager.GetString("EnabledShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Submission.
        /// </summary>
        public static string LastSubmission {
            get {
                return ResourceManager.GetString("LastSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sub.
        /// </summary>
        public static string LastSubmissionShort {
            get {
                return ResourceManager.GetString("LastSubmissionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Count.
        /// </summary>
        public static string PublishedCount {
            get {
                return ResourceManager.GetString("PublishedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string PublishedCountShort {
            get {
                return ResourceManager.GetString("PublishedCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Count.
        /// </summary>
        public static string RelatedCount {
            get {
                return ResourceManager.GetString("RelatedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC.
        /// </summary>
        public static string RelatedCountShort {
            get {
                return ResourceManager.GetString("RelatedCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Date.
        /// </summary>
        public static string ResponseDate {
            get {
                return ResourceManager.GetString("ResponseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Type.
        /// </summary>
        public static string ResponseType {
            get {
                return ResourceManager.GetString("ResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ResponseTypeShort {
            get {
                return ResourceManager.GetString("ResponseTypeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Submission Count.
        /// </summary>
        public static string SubmissionCurrentCount {
            get {
                return ResourceManager.GetString("SubmissionCurrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS.
        /// </summary>
        public static string SubmissionCurrentCountShort {
            get {
                return ResourceManager.GetString("SubmissionCurrentCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Submission Count.
        /// </summary>
        public static string SubmissionTotalCount {
            get {
                return ResourceManager.GetString("SubmissionTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.
        /// </summary>
        public static string SubmissionTotalCountShort {
            get {
                return ResourceManager.GetString("SubmissionTotalCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Count.
        /// </summary>
        public static string TagCount {
            get {
                return ResourceManager.GetString("TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC.
        /// </summary>
        public static string TagCountShort {
            get {
                return ResourceManager.GetString("TagCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Count.
        /// </summary>
        public static string VersionCount {
            get {
                return ResourceManager.GetString("VersionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC.
        /// </summary>
        public static string VersionCountShort {
            get {
                return ResourceManager.GetString("VersionCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        public static string WordCount {
            get {
                return ResourceManager.GetString("WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WC.
        /// </summary>
        public static string WordCountShort {
            get {
                return ResourceManager.GetString("WordCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written.
        /// </summary>
        public static string Written {
            get {
                return ResourceManager.GetString("Written", resourceCulture);
            }
        }
    }
}
