//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Header {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Header() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Header", typeof(Header).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Alerts.
        /// </summary>
        public static string ActiveAlerts {
            get {
                return ResourceManager.GetString("ActiveAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Tags.
        /// </summary>
        public static string AssignedTags {
            get {
                return ResourceManager.GetString("AssignedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Tags.
        /// </summary>
        public static string AvailableTags {
            get {
                return ResourceManager.GetString("AvailableTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Column.
        /// </summary>
        public static string ChildColumn {
            get {
                return ResourceManager.GetString("ChildColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string ChildRelationShort {
            get {
                return ResourceManager.GetString("ChildRelationShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Table.
        /// </summary>
        public static string ChildTable {
            get {
                return ResourceManager.GetString("ChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cols.
        /// </summary>
        public static string ColumnsShort {
            get {
                return ResourceManager.GetString("ColumnsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm title submission.
        /// </summary>
        public static string ConfirmTitleSubmission {
            get {
                return ResourceManager.GetString("ConfirmTitleSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string ConstraintShort {
            get {
                return ResourceManager.GetString("ConstraintShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string DefaultShort {
            get {
                return ResourceManager.GetString("DefaultShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rule.
        /// </summary>
        public static string DeleteRule {
            get {
                return ResourceManager.GetString("DeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string EnabledShort {
            get {
                return ResourceManager.GetString("EnabledShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string ErrorShort {
            get {
                return ResourceManager.GetString("ErrorShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive.
        /// </summary>
        public static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string ExclusiveShort {
            get {
                return ResourceManager.GetString("ExclusiveShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        public static string InUseShort {
            get {
                return ResourceManager.GetString("InUseShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.
        /// </summary>
        public static string LanguageShort {
            get {
                return ResourceManager.GetString("LanguageShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Submission.
        /// </summary>
        public static string LastSubmission {
            get {
                return ResourceManager.GetString("LastSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sub.
        /// </summary>
        public static string LastSubmissionShort {
            get {
                return ResourceManager.GetString("LastSubmissionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Name.
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Name.
        /// </summary>
        public static string OldName {
            get {
                return ResourceManager.GetString("OldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering.
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string OrderingShort {
            get {
                return ResourceManager.GetString("OrderingShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Column.
        /// </summary>
        public static string ParentColumn {
            get {
                return ResourceManager.GetString("ParentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR.
        /// </summary>
        public static string ParentRelationShort {
            get {
                return ResourceManager.GetString("ParentRelationShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Table.
        /// </summary>
        public static string ParentTable {
            get {
                return ResourceManager.GetString("ParentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Count.
        /// </summary>
        public static string PublishedCount {
            get {
                return ResourceManager.GetString("PublishedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string PublishedCountShort {
            get {
                return ResourceManager.GetString("PublishedCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher Filter.
        /// </summary>
        public static string PublisherFilter {
            get {
                return ResourceManager.GetString("PublisherFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick.
        /// </summary>
        public static string Quick {
            get {
                return ResourceManager.GetString("Quick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string QuickShort {
            get {
                return ResourceManager.GetString("QuickShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string ReadyShort {
            get {
                return ResourceManager.GetString("ReadyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Count.
        /// </summary>
        public static string RelatedCount {
            get {
                return ResourceManager.GetString("RelatedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC.
        /// </summary>
        public static string RelatedCountShort {
            get {
                return ResourceManager.GetString("RelatedCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Date.
        /// </summary>
        public static string ResponseDate {
            get {
                return ResourceManager.GetString("ResponseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Type.
        /// </summary>
        public static string ResponseType {
            get {
                return ResourceManager.GetString("ResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev.
        /// </summary>
        public static string RevisionShort {
            get {
                return ResourceManager.GetString("RevisionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string Scanned {
            get {
                return ResourceManager.GetString("Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select messages.
        /// </summary>
        public static string SelectMessagesGeneric {
            get {
                return ResourceManager.GetString("SelectMessagesGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a publisher for this published record.
        /// </summary>
        public static string SelectPublisherForPublished {
            get {
                return ResourceManager.GetString("SelectPublisherForPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a publisher.
        /// </summary>
        public static string SelectPublisherGeneric {
            get {
                return ResourceManager.GetString("SelectPublisherGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select titles.
        /// </summary>
        public static string SelectTitlesGeneric {
            get {
                return ResourceManager.GetString("SelectTitlesGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Published.
        /// </summary>
        public static string SelfPublished {
            get {
                return ResourceManager.GetString("SelfPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Publishers.
        /// </summary>
        public static string SelfPublishers {
            get {
                return ResourceManager.GetString("SelfPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string StatusShort {
            get {
                return ResourceManager.GetString("StatusShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Submission Count.
        /// </summary>
        public static string SubmissionCurrentCount {
            get {
                return ResourceManager.GetString("SubmissionCurrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS.
        /// </summary>
        public static string SubmissionCurrentCountShort {
            get {
                return ResourceManager.GetString("SubmissionCurrentCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Data.
        /// </summary>
        public static string SubmissionMetadata {
            get {
                return ResourceManager.GetString("SubmissionMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string Submissions {
            get {
                return ResourceManager.GetString("Submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Submission Count.
        /// </summary>
        public static string SubmissionTotalCount {
            get {
                return ResourceManager.GetString("SubmissionTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.
        /// </summary>
        public static string SubmissionTotalCountShort {
            get {
                return ResourceManager.GetString("SubmissionTotalCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Count.
        /// </summary>
        public static string TagCount {
            get {
                return ResourceManager.GetString("TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC.
        /// </summary>
        public static string TagCountShort {
            get {
                return ResourceManager.GetString("TagCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag filter.
        /// </summary>
        public static string TagFilter {
            get {
                return ResourceManager.GetString("TagFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Filter.
        /// </summary>
        public static string TitleFilter {
            get {
                return ResourceManager.GetString("TitleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title List.
        /// </summary>
        public static string TitleList {
            get {
                return ResourceManager.GetString("TitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Data.
        /// </summary>
        public static string TitleMetadata {
            get {
                return ResourceManager.GetString("TitleMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename title version files.
        /// </summary>
        public static string TitleVersionRename {
            get {
                return ResourceManager.GetString("TitleVersionRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Count.
        /// </summary>
        public static string VersionCount {
            get {
                return ResourceManager.GetString("VersionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC.
        /// </summary>
        public static string VersionCountShort {
            get {
                return ResourceManager.GetString("VersionCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        public static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string VersionShort {
            get {
                return ResourceManager.GetString("VersionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        public static string WordCount {
            get {
                return ResourceManager.GetString("WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WC.
        /// </summary>
        public static string WordCountShort {
            get {
                return ResourceManager.GetString("WordCountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written.
        /// </summary>
        public static string Written {
            get {
                return ResourceManager.GetString("Written", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xid.
        /// </summary>
        public static string Xid {
            get {
                return ResourceManager.GetString("Xid", resourceCulture);
            }
        }
    }
}
