//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an alert.
        /// </summary>
        public static string AddAlert {
            get {
                return ResourceManager.GetString("AddAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an author.
        /// </summary>
        public static string AddAuthor {
            get {
                return ResourceManager.GetString("AddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a document to this submission.
        /// </summary>
        public static string AddDocumentToSubmission {
            get {
                return ResourceManager.GetString("AddDocumentToSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link.
        /// </summary>
        public static string AddLink {
            get {
                return ResourceManager.GetString("AddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a published record to this title.
        /// </summary>
        public static string AddPublished {
            get {
                return ResourceManager.GetString("AddPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a queue.
        /// </summary>
        public static string AddQueue {
            get {
                return ResourceManager.GetString("AddQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add related titles to this title.
        /// </summary>
        public static string AddRelated {
            get {
                return ResourceManager.GetString("AddRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a self published record to this title.
        /// </summary>
        public static string AddSelfPublished {
            get {
                return ResourceManager.GetString("AddSelfPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a message to this submission.
        /// </summary>
        public static string AddSubmissionMessage {
            get {
                return ResourceManager.GetString("AddSubmissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a submission period.
        /// </summary>
        public static string AddSubmissionPeriod {
            get {
                return ResourceManager.GetString("AddSubmissionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a title to the collection.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add title(s) to this submission.
        /// </summary>
        public static string AddTitleToSubmission {
            get {
                return ResourceManager.GetString("AddTitleToSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an existing file as a version.
        /// </summary>
        public static string AddTitleVersion {
            get {
                return ResourceManager.GetString("AddTitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        public static string AddToQueue {
            get {
                return ResourceManager.GetString("AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note.
        /// </summary>
        public static string AddUserNote {
            get {
                return ResourceManager.GetString("AddUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to this publisher&apos;s web site.
        /// </summary>
        public static string BrowseToPublisherUrl {
            get {
                return ResourceManager.GetString("BrowseToPublisherUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to this publisher&apos;s web site (or double click the row).
        /// </summary>
        public static string BrowseToPublisherUrlOrClick {
            get {
                return ResourceManager.GetString("BrowseToPublisherUrlOrClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to this url (or double click the row).
        /// </summary>
        public static string BrowseToUrlOrClick {
            get {
                return ResourceManager.GetString("BrowseToUrlOrClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the published date.
        /// </summary>
        public static string ClearPublishedDate {
            get {
                return ResourceManager.GetString("ClearPublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy title to clipboard.
        /// </summary>
        public static string CopyTitle {
            get {
                return ResourceManager.GetString("CopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new publisher record.
        /// </summary>
        public static string CreatePublisher {
            get {
                return ResourceManager.GetString("CreatePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a submission.
        /// </summary>
        public static string CreateSubmission {
            get {
                return ResourceManager.GetString("CreateSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a title entry from this file.
        /// </summary>
        public static string CreateTitleFromEntry {
            get {
                return ResourceManager.GetString("CreateTitleFromEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new title version from a copy of the latest version.
        /// </summary>
        public static string CreateTitleVersionCopy {
            get {
                return ResourceManager.GetString("CreateTitleVersionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this alert.
        /// </summary>
        public static string DeleteAlert {
            get {
                return ResourceManager.GetString("DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this author.
        /// </summary>
        public static string DeleteAuthor {
            get {
                return ResourceManager.GetString("DeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this link.
        /// </summary>
        public static string DeleteLink {
            get {
                return ResourceManager.GetString("DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this note.
        /// </summary>
        public static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this publisher.
        /// </summary>
        public static string DeletePublisher {
            get {
                return ResourceManager.GetString("DeletePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this submission.
        /// </summary>
        public static string DeleteSubmission {
            get {
                return ResourceManager.GetString("DeleteSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this tag.
        /// </summary>
        public static string DeleteTag {
            get {
                return ResourceManager.GetString("DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this title.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude this directory from orphan search.
        /// </summary>
        public static string ExcludeOrphanDirectory {
            get {
                return ResourceManager.GetString("ExcludeOrphanDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude this file from orphan search.
        /// </summary>
        public static string ExcludeOrphanFile {
            get {
                return ResourceManager.GetString("ExcludeOrphanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude all files of this type from orphan search.
        /// </summary>
        public static string ExcludeOrphanFileType {
            get {
                return ResourceManager.GetString("ExcludeOrphanFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter title list to selected title and its related titles.
        /// </summary>
        public static string FilterTitleListToRelated {
            get {
                return ResourceManager.GetString("FilterTitleListToRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter list to display only submissions to this publisher.
        /// </summary>
        public static string FilterToPublisher {
            get {
                return ResourceManager.GetString("FilterToPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged.
        /// </summary>
        public static string Flagged {
            get {
                return ResourceManager.GetString("Flagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle flag for this title.
        /// </summary>
        public static string FlagTitle {
            get {
                return ResourceManager.GetString("FlagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Period.
        /// </summary>
        public static string InPeriod {
            get {
                return ResourceManager.GetString("InPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make this a separate version.
        /// </summary>
        public static string MakeSeparateVersion {
            get {
                return ResourceManager.GetString("MakeSeparateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this item (or double click the row).
        /// </summary>
        public static string OpenItemOrDoubleClick {
            get {
                return ResourceManager.GetString("OpenItemOrDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the latest version of this title (or double click the row).
        /// </summary>
        public static string OpenTitleOrDoubleClick {
            get {
                return ResourceManager.GetString("OpenTitleOrDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying.
        /// </summary>
        public static string Paying {
            get {
                return ResourceManager.GetString("Paying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this exclusion.
        /// </summary>
        public static string RemoveExclusion {
            get {
                return ResourceManager.GetString("RemoveExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove title from selected queue.
        /// </summary>
        public static string RemoveFromQueue {
            get {
                return ResourceManager.GetString("RemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this published record.
        /// </summary>
        public static string RemovePublished {
            get {
                return ResourceManager.GetString("RemovePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this queue.
        /// </summary>
        public static string RemoveQueue {
            get {
                return ResourceManager.GetString("RemoveQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this title from queue.
        /// </summary>
        public static string RemoveQueueTitle {
            get {
                return ResourceManager.GetString("RemoveQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this related title.
        /// </summary>
        public static string RemoveRelated {
            get {
                return ResourceManager.GetString("RemoveRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this document from submission.
        /// </summary>
        public static string RemoveSubmissionDocument {
            get {
                return ResourceManager.GetString("RemoveSubmissionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this message from submission.
        /// </summary>
        public static string RemoveSubmissionMessage {
            get {
                return ResourceManager.GetString("RemoveSubmissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this submission period.
        /// </summary>
        public static string RemoveSubmissionPeriod {
            get {
                return ResourceManager.GetString("RemoveSubmissionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove title from submission.
        /// </summary>
        public static string RemoveTitleFromSubmission {
            get {
                return ResourceManager.GetString("RemoveTitleFromSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this title version.
        /// </summary>
        public static string RemoveTitleVersion {
            get {
                return ResourceManager.GetString("RemoveTitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename this queue.
        /// </summary>
        public static string RenameQueue {
            get {
                return ResourceManager.GetString("RenameQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace this submission document.
        /// </summary>
        public static string ReplaceSubmissionDocument {
            get {
                return ResourceManager.GetString("ReplaceSubmissionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the file for this version with another file.
        /// </summary>
        public static string ReplaceTitleVersion {
            get {
                return ResourceManager.GetString("ReplaceTitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set status to accepted.
        /// </summary>
        public static string SetTitleStatusAccepted {
            get {
                return ResourceManager.GetString("SetTitleStatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set status to none.
        /// </summary>
        public static string SetTitleStatusNone {
            get {
                return ResourceManager.GetString("SetTitleStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set status to withdrawn.
        /// </summary>
        public static string SetTitleStatusWithdrawn {
            get {
                return ResourceManager.GetString("SetTitleStatusWithdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        public static string Withdrawn {
            get {
                return ResourceManager.GetString("Withdrawn", resourceCulture);
            }
        }
    }
}
