//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto sort title list on updated (requires restart).
        /// </summary>
        public static string AutoSortOnUpdated {
            get {
                return ResourceManager.GetString("AutoSortOnUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Location.
        /// </summary>
        public static string DatabaseLocation {
            get {
                return ResourceManager.GetString("DatabaseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the database location will create a new database. No data will be copied. If you want to preserve your data, copy all files from the previous location to the new one.
        ///
        ///Changes will take effect after you restart the application..
        /// </summary>
        public static string DatabaseLocationText {
            get {
                return ResourceManager.GetString("DatabaseLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data grid row alternation.
        /// </summary>
        public static string DataGridRowAlternation {
            get {
                return ResourceManager.GetString("DataGridRowAlternation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data grid row height.
        /// </summary>
        public static string DataGridRowHeight {
            get {
                return ResourceManager.GetString("DataGridRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable developer tools.
        /// </summary>
        public static string DeveloperTool {
            get {
                return ResourceManager.GetString("DeveloperTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Navigator Header.
        /// </summary>
        public static string NavigatorHeader {
            get {
                return ResourceManager.GetString("NavigatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable orphan finder tool.
        /// </summary>
        public static string OrphanFinder {
            get {
                return ResourceManager.GetString("OrphanFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable title queues.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable search tool.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Viewer.
        /// </summary>
        public static string TextViewer {
            get {
                return ResourceManager.GetString("TextViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable link verification tool (experimental).
        /// </summary>
        public static string VerifyLinks {
            get {
                return ResourceManager.GetString("VerifyLinks", resourceCulture);
            }
        }
    }
}
