//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a submission document.
        /// </summary>
        public static string CaptionSelectSubmissionDocument {
            get {
                return ResourceManager.GetString("CaptionSelectSubmissionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to add to the versions of this title.
        /// </summary>
        public static string CaptionSelectTitleVersionAddByFile {
            get {
                return ResourceManager.GetString("CaptionSelectTitleVersionAddByFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to replace the file of the selected version.
        /// </summary>
        public static string CaptionSelectTitleVersionReplaceByFile {
            get {
                return ResourceManager.GetString("CaptionSelectTitleVersionReplaceByFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a submission to {0}?.
        /// </summary>
        public static string FormatStringCreateSubmission {
            get {
                return ResourceManager.GetString("FormatStringCreateSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: You already have at least one submission to this publisher that has not yet received a response. Do you want to continue and create another submission?.
        /// </summary>
        public static string FormatStringCreateSubmissionOpen {
            get {
                return ResourceManager.GetString("FormatStringCreateSubmissionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist.
        ///
        ///{0}
        ///
        ///Please make sure that {1} is set correctly in configuration settings. File specifications are relative to this setting..
        /// </summary>
        public static string FormatStringFileNotFound {
            get {
                return ResourceManager.GetString("FormatStringFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder contains exported versions of each title tracked by {0}.
        ///Files are named according to the date they were first written, title, version, and language.
        ///
        ///Usually, the individual files are kept in different sub directories; this directory has all files in one place.
        ///
        ///Last exported: {1}.
        /// </summary>
        public static string FormatTextExport {
            get {
                return ResourceManager.GetString("FormatTextExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory that will hold the database files.
        /// </summary>
        public static string InstallationCaption {
            get {
                return ResourceManager.GetString("InstallationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has already been added to this title. Please choose a different file..
        /// </summary>
        public static string InvalidOpCannotAddVersionFile {
            get {
                return ResourceManager.GetString("InvalidOpCannotAddVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author cannot be deleted. They are participating in {0} titles. .
        /// </summary>
        public static string InvalidOpCannotDeleteAuthor {
            get {
                return ResourceManager.GetString("InvalidOpCannotDeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This publisher cannot be deleted. It is participating in {0} submissions. .
        /// </summary>
        public static string InvalidOpCannotDeletePublisher {
            get {
                return ResourceManager.GetString("InvalidOpCannotDeletePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag cannot be deleted. It is being used by {0} titles. .
        /// </summary>
        public static string InvalidOpCannotDeleteTag {
            get {
                return ResourceManager.GetString("InvalidOpCannotDeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title cannot be deleted. It is participating in {0} submissions. .
        /// </summary>
        public static string InvalidOpCannotDeleteTitle {
            get {
                return ResourceManager.GetString("InvalidOpCannotDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message contents can&apos;t be displayed here. This message is a direct reference to the item stored in the Outlook message store. Double click the row to open the message..
        /// </summary>
        public static string InvalidOpCannotDisplayMapi {
            get {
                return ResourceManager.GetString("InvalidOpCannotDisplayMapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is not supported.
        /// </summary>
        public static string InvalidOpCommandNotSupported {
            get {
                return ResourceManager.GetString("InvalidOpCommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exist.
        /// </summary>
        public static string InvalidOpDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("InvalidOpDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document type is obsolete and is no longer supported.
        /// </summary>
        public static string InvalidOpDocumentTypeNotSupported {
            get {
                return ResourceManager.GetString("InvalidOpDocumentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search scope specified.
        /// </summary>
        public static string InvalidOperationNoSearchScope {
            get {
                return ResourceManager.GetString("InvalidOperationNoSearchScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Outlook folder  from which to select submission messages hasn&apos;t been set. Fix the configuration and try again..
        /// </summary>
        public static string InvalidOpMapiFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpMapiFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open. There is no document associated with this entry..
        /// </summary>
        public static string InvalidOpNoDocumentId {
            get {
                return ResourceManager.GetString("InvalidOpNoDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough text to scramble. Paste some more text and try again..
        /// </summary>
        public static string InvalidOpNotEnoughTextToScramble {
            get {
                return ResourceManager.GetString("InvalidOpNotEnoughTextToScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for this operation hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string InvalidOpOutputFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpOutputFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the version files for this title have already been renamed..
        /// </summary>
        public static string InvalidOpRenameAllCandidatesAlreadyRenamed {
            get {
                return ResourceManager.GetString("InvalidOpRenameAllCandidatesAlreadyRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions exist to rename.
        /// </summary>
        public static string InvalidOpRenameCandidateListEmpty {
            get {
                return ResourceManager.GetString("InvalidOpRenameCandidateListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be completed because the file for version {0}
        ///
        ///{1} 
        ///
        ///does not exist. Correct this by selecting the correct file and then try again..
        /// </summary>
        public static string InvalidOpRenameFileDoesNotExistFormat {
            get {
                return ResourceManager.GetString("InvalidOpRenameFileDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the version files does not exist.
        /// </summary>
        public static string InvalidOpRenameFilesMissing {
            get {
                return ResourceManager.GetString("InvalidOpRenameFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for submission documents hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string InvalidOpSubmissionDocumentFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpSubmissionDocumentFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for submission messages has not been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string InvalidOpSubmissionMessageFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpSubmissionMessageFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external text viewer application has not been set. Fix the configuration setting and try again..
        /// </summary>
        public static string InvalidOpTextViewerNotSet {
            get {
                return ResourceManager.GetString("InvalidOpTextViewerNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified title record does not exist.
        /// </summary>
        public static string InvalidOpTitleDoesNotExist {
            get {
                return ResourceManager.GetString("InvalidOpTitleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output folder for the title list operation does not exist..
        /// </summary>
        public static string InvalidOpTitleListOutputFolder {
            get {
                return ResourceManager.GetString("InvalidOpTitleListOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title root folder hasn&apos;t been set or doesn&apos;t exist. Fix the configuration setting and try again..
        /// </summary>
        public static string InvalidOpTitleRootFolderNotSet {
            get {
                return ResourceManager.GetString("InvalidOpTitleRootFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot exit at this time. Background tasks are still running..
        /// </summary>
        public static string NotificationCannotExitTasksAreRunning {
            get {
                return ResourceManager.GetString("NotificationCannotExitTasksAreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission created.
        /// </summary>
        public static string ResultSubmissionCreated {
            get {
                return ResourceManager.GetString("ResultSubmissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added / Updated.
        /// </summary>
        public static string TextAddedUpdated {
            get {
                return ResourceManager.GetString("TextAddedUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now terminate.
        /// </summary>
        public static string TextApplicationTerminate {
            get {
                return ResourceManager.GetString("TextApplicationTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string TextAssigned {
            get {
                return ResourceManager.GetString("TextAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags to filter.
        /// </summary>
        public static string TextAssignedToFilter {
            get {
                return ResourceManager.GetString("TextAssignedToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string TextAvailable {
            get {
                return ResourceManager.GetString("TextAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tags.
        /// </summary>
        public static string TextAvailableTags {
            get {
                return ResourceManager.GetString("TextAvailableTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string TextClear {
            get {
                return ResourceManager.GetString("TextClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear date.
        /// </summary>
        public static string TextClearDate {
            get {
                return ResourceManager.GetString("TextClearDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string TextConfirm {
            get {
                return ResourceManager.GetString("TextConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry was created from orphan file.
        /// </summary>
        public static string TextCreatedFromOrphan {
            get {
                return ResourceManager.GetString("TextCreatedFromOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create submission document.
        /// </summary>
        public static string TextCreateSubmissionDocument0 {
            get {
                return ResourceManager.GetString("TextCreateSubmissionDocument0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to create a submission document. You may:.
        /// </summary>
        public static string TextCreateSubmissionDocument1 {
            get {
                return ResourceManager.GetString("TextCreateSubmissionDocument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a .docx document compatible with Microsoft Word and other word processors that support the Open XML specification..
        /// </summary>
        public static string TextCreateSubmissionDocument2 {
            get {
                return ResourceManager.GetString("TextCreateSubmissionDocument2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a placeholder entry in the submission documents. After, you can select an existing file to associate with this entry..
        /// </summary>
        public static string TextCreateSubmissionDocument3 {
            get {
                return ResourceManager.GetString("TextCreateSubmissionDocument3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .docx.
        /// </summary>
        public static string TextCreateSubmissionDocument4 {
            get {
                return ResourceManager.GetString("TextCreateSubmissionDocument4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create placeholder.
        /// </summary>
        public static string TextCreateSubmissionDocument5 {
            get {
                return ResourceManager.GetString("TextCreateSubmissionDocument5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string TextDark {
            get {
                return ResourceManager.GetString("TextDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TextDate {
            get {
                return ResourceManager.GetString("TextDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string TextDays01 {
            get {
                return ResourceManager.GetString("TextDays01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days.
        /// </summary>
        public static string TextDays03 {
            get {
                return ResourceManager.GetString("TextDays03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 days.
        /// </summary>
        public static string TextDays05 {
            get {
                return ResourceManager.GetString("TextDays05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        public static string TextDays07 {
            get {
                return ResourceManager.GetString("TextDays07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 days.
        /// </summary>
        public static string TextDays10 {
            get {
                return ResourceManager.GetString("TextDays10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TextDescription {
            get {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string TextDetail {
            get {
                return ResourceManager.GetString("TextDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string TextDismiss {
            get {
                return ResourceManager.GetString("TextDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Preview Not Supported.
        /// </summary>
        public static string TextDocumentPreviewNotSupported {
            get {
                return ResourceManager.GetString("TextDocumentPreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string TextEnabled {
            get {
                return ResourceManager.GetString("TextEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ever Submitted.
        /// </summary>
        public static string TextEverSubmitted {
            get {
                return ResourceManager.GetString("TextEverSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string TextExtract {
            get {
                return ResourceManager.GetString("TextExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged.
        /// </summary>
        public static string TextFlagged {
            get {
                return ResourceManager.GetString("TextFlagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Related Title.
        /// </summary>
        public static string TextHasRelated {
            get {
                return ResourceManager.GetString("TextHasRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string TextHidden {
            get {
                return ResourceManager.GetString("TextHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string TextImage {
            get {
                return ResourceManager.GetString("TextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string TextLight {
            get {
                return ResourceManager.GetString("TextLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string TextLocked {
            get {
                return ResourceManager.GetString("TextLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine multiple.
        /// </summary>
        public static string TextMultipleTag {
            get {
                return ResourceManager.GetString("TextMultipleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string TextNone {
            get {
                return ResourceManager.GetString("TextNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submission periods defined for this publisher.
        /// </summary>
        public static string TextNoPublisherPeriods {
            get {
                return ResourceManager.GetString("TextNoPublisherPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submissions to this publisher.
        /// </summary>
        public static string TextNoPublisherSubmissions {
            get {
                return ResourceManager.GetString("TextNoPublisherSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string TextNote {
            get {
                return ResourceManager.GetString("TextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TextNotes {
            get {
                return ResourceManager.GetString("TextNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No titles.
        /// </summary>
        public static string TextNoTitles {
            get {
                return ResourceManager.GetString("TextNoTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submissions for this title.
        /// </summary>
        public static string TextNoTitleSubmissions {
            get {
                return ResourceManager.GetString("TextNoTitleSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions for this title.
        /// </summary>
        public static string TextNoTitleVersions {
            get {
                return ResourceManager.GetString("TextNoTitleVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Open Xml Document.
        /// </summary>
        public static string TextNotOpenXmlDocument {
            get {
                return ResourceManager.GetString("TextNotOpenXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphan.
        /// </summary>
        public static string TextOrphan {
            get {
                return ResourceManager.GetString("TextOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphans.
        /// </summary>
        public static string TextOrphans {
            get {
                return ResourceManager.GetString("TextOrphans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string TextPreview {
            get {
                return ResourceManager.GetString("TextPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string TextPublished {
            get {
                return ResourceManager.GetString("TextPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string TextPublisher {
            get {
                return ResourceManager.GetString("TextPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string TextReady {
            get {
                return ResourceManager.GetString("TextReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record.
        /// </summary>
        public static string TextRecord {
            get {
                return ResourceManager.GetString("TextRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        public static string TextRecords {
            get {
                return ResourceManager.GetString("TextRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string TextRefresh {
            get {
                return ResourceManager.GetString("TextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string TextRemoved {
            get {
                return ResourceManager.GetString("TextRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string TextRename {
            get {
                return ResourceManager.GetString("TextRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string TextResponse {
            get {
                return ResourceManager.GetString("TextResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Published.
        /// </summary>
        public static string TextSelfPublished {
            get {
                return ResourceManager.GetString("TextSelfPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send report.
        /// </summary>
        public static string TextSendReport {
            get {
                return ResourceManager.GetString("TextSendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string TextStartup {
            get {
                return ResourceManager.GetString("TextStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string TextSubmitted {
            get {
                return ResourceManager.GetString("TextSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string TextUrl {
            get {
                return ResourceManager.GetString("TextUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string TextVerify {
            get {
                return ResourceManager.GetString("TextVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written.
        /// </summary>
        public static string TextWritten {
            get {
                return ResourceManager.GetString("TextWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search returned no results.
        /// </summary>
        public static string TextZeroSearchResults {
            get {
                return ResourceManager.GetString("TextZeroSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to submit the following titles.
        /// </summary>
        public static string TitleStatusHeader {
            get {
                return ResourceManager.GetString("TitleStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conflict.
        /// </summary>
        public static string TitleStatusOkay {
            get {
                return ResourceManager.GetString("TitleStatusOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously submitted to the same publisher.
        /// </summary>
        public static string TitleStatusPreviousToPublisher {
            get {
                return ResourceManager.GetString("TitleStatusPreviousToPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently submitted to a publisher that does not accept simultaneous submissions.
        /// </summary>
        public static string TitleStatusSubmittedToExclusive {
            get {
                return ResourceManager.GetString("TitleStatusSubmittedToExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status.
        /// </summary>
        public static string TitleStatusUnknown {
            get {
                return ResourceManager.GetString("TitleStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Alerts.
        /// </summary>
        public static string WindowTitleActiveAlerts {
            get {
                return ResourceManager.GetString("WindowTitleActiveAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm title submission.
        /// </summary>
        public static string WindowTitleConfirmTitleSubmission {
            get {
                return ResourceManager.GetString("WindowTitleConfirmTitleSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string WindowTitleFatalError {
            get {
                return ResourceManager.GetString("WindowTitleFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select messages.
        /// </summary>
        public static string WindowTitleSelectMessagesGeneric {
            get {
                return ResourceManager.GetString("WindowTitleSelectMessagesGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a publisher for this published record.
        /// </summary>
        public static string WindowTitleSelectPublisherForPublished {
            get {
                return ResourceManager.GetString("WindowTitleSelectPublisherForPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a publisher.
        /// </summary>
        public static string WindowTitleSelectPublisherGeneric {
            get {
                return ResourceManager.GetString("WindowTitleSelectPublisherGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select titles.
        /// </summary>
        public static string WindowTitleSelectTitlesGeneric {
            get {
                return ResourceManager.GetString("WindowTitleSelectTitlesGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename title version files.
        /// </summary>
        public static string WindowTitleVersionRename {
            get {
                return ResourceManager.GetString("WindowTitleVersionRename", resourceCulture);
            }
        }
    }
}
