//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added / Updated.
        /// </summary>
        public static string AddedUpdated {
            get {
                return ResourceManager.GetString("AddedUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Year.
        /// </summary>
        public static string AllYear {
            get {
                return ResourceManager.GetString("AllYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now terminate.
        /// </summary>
        public static string ApplicationTerminate {
            get {
                return ResourceManager.GetString("ApplicationTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags to filter.
        /// </summary>
        public static string AssignedToFilter {
            get {
                return ResourceManager.GetString("AssignedToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tags.
        /// </summary>
        public static string AvailableTags {
            get {
                return ResourceManager.GetString("AvailableTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Days.
        /// </summary>
        public static string AverageDays {
            get {
                return ResourceManager.GetString("AverageDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear date.
        /// </summary>
        public static string ClearDate {
            get {
                return ResourceManager.GetString("ClearDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry was created from orphan file.
        /// </summary>
        public static string CreatedFromOrphan {
            get {
                return ResourceManager.GetString("CreatedFromOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create submission document.
        /// </summary>
        public static string CreateSubmissionDocument0 {
            get {
                return ResourceManager.GetString("CreateSubmissionDocument0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to create a submission document. You may:.
        /// </summary>
        public static string CreateSubmissionDocument1 {
            get {
                return ResourceManager.GetString("CreateSubmissionDocument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a .docx document compatible with Microsoft Word and other word processors that support the Open XML specification..
        /// </summary>
        public static string CreateSubmissionDocument2 {
            get {
                return ResourceManager.GetString("CreateSubmissionDocument2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a placeholder entry in the submission documents. After, you can select an existing file to associate with this entry..
        /// </summary>
        public static string CreateSubmissionDocument3 {
            get {
                return ResourceManager.GetString("CreateSubmissionDocument3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .docx.
        /// </summary>
        public static string CreateSubmissionDocument4 {
            get {
                return ResourceManager.GetString("CreateSubmissionDocument4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create placeholder.
        /// </summary>
        public static string CreateSubmissionDocument5 {
            get {
                return ResourceManager.GetString("CreateSubmissionDocument5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string Days01 {
            get {
                return ResourceManager.GetString("Days01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days.
        /// </summary>
        public static string Days03 {
            get {
                return ResourceManager.GetString("Days03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 days.
        /// </summary>
        public static string Days05 {
            get {
                return ResourceManager.GetString("Days05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        public static string Days07 {
            get {
                return ResourceManager.GetString("Days07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 days.
        /// </summary>
        public static string Days10 {
            get {
                return ResourceManager.GetString("Days10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default author.
        /// </summary>
        public static string DefaultAuthor {
            get {
                return ResourceManager.GetString("DefaultAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ever Submitted.
        /// </summary>
        public static string EverSubmitted {
            get {
                return ResourceManager.GetString("EverSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive.
        /// </summary>
        public static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive (no simultaneous).
        /// </summary>
        public static string ExclusiveNoSim {
            get {
                return ResourceManager.GetString("ExclusiveNoSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged.
        /// </summary>
        public static string Flagged {
            get {
                return ResourceManager.GetString("Flagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string FollowUp {
            get {
                return ResourceManager.GetString("FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goner.
        /// </summary>
        public static string Goner {
            get {
                return ResourceManager.GetString("Goner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Related Title.
        /// </summary>
        public static string HasRelated {
            get {
                return ResourceManager.GetString("HasRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Period.
        /// </summary>
        public static string InPeriod {
            get {
                return ResourceManager.GetString("InPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change requested. Restart the application to apply the new language..
        /// </summary>
        public static string LanguageChangeRequested {
            get {
                return ResourceManager.GetString("LanguageChangeRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Days.
        /// </summary>
        public static string MaxDays {
            get {
                return ResourceManager.GetString("MaxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Days.
        /// </summary>
        public static string MinDays {
            get {
                return ResourceManager.GetString("MinDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine multiple.
        /// </summary>
        public static string MultipleTag {
            get {
                return ResourceManager.GetString("MultipleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submission periods defined for this publisher.
        /// </summary>
        public static string NoPublisherPeriods {
            get {
                return ResourceManager.GetString("NoPublisherPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submissions to this publisher.
        /// </summary>
        public static string NoPublisherSubmissions {
            get {
                return ResourceManager.GetString("NoPublisherSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no title).
        /// </summary>
        public static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No titles.
        /// </summary>
        public static string NoTitles {
            get {
                return ResourceManager.GetString("NoTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submissions for this title.
        /// </summary>
        public static string NoTitleSubmissions {
            get {
                return ResourceManager.GetString("NoTitleSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions for this title.
        /// </summary>
        public static string NoTitleVersions {
            get {
                return ResourceManager.GetString("NoTitleVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Open Xml Document.
        /// </summary>
        public static string NotOpenXmlDocument {
            get {
                return ResourceManager.GetString("NotOpenXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Submission.
        /// </summary>
        public static string OpenSubmission {
            get {
                return ResourceManager.GetString("OpenSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphan.
        /// </summary>
        public static string Orphan {
            get {
                return ResourceManager.GetString("Orphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphans.
        /// </summary>
        public static string Orphans {
            get {
                return ResourceManager.GetString("Orphans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying.
        /// </summary>
        public static string Paying {
            get {
                return ResourceManager.GetString("Paying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postone.
        /// </summary>
        public static string Postpone {
            get {
                return ResourceManager.GetString("Postpone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [row filter in effect].
        /// </summary>
        public static string RowFilterInEffect {
            get {
                return ResourceManager.GetString("RowFilterInEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Published.
        /// </summary>
        public static string SelfPublished {
            get {
                return ResourceManager.GetString("SelfPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send report.
        /// </summary>
        public static string SendReport {
            get {
                return ResourceManager.GetString("SendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission created.
        /// </summary>
        public static string SubmissionCreated {
            get {
                return ResourceManager.GetString("SubmissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conflict.
        /// </summary>
        public static string TitleStatusOkay {
            get {
                return ResourceManager.GetString("TitleStatusOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously submitted to the same publisher.
        /// </summary>
        public static string TitleStatusPreviousToPublisher {
            get {
                return ResourceManager.GetString("TitleStatusPreviousToPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently submitted to a publisher that does not accept simultaneous submissions.
        /// </summary>
        public static string TitleStatusSubmittedToExclusive {
            get {
                return ResourceManager.GetString("TitleStatusSubmittedToExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status.
        /// </summary>
        public static string TitleStatusUnknown {
            get {
                return ResourceManager.GetString("TitleStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        public static string WordCount {
            get {
                return ResourceManager.GetString("WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written.
        /// </summary>
        public static string Written {
            get {
                return ResourceManager.GetString("Written", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search returned no results.
        /// </summary>
        public static string ZeroSearchResults {
            get {
                return ResourceManager.GetString("ZeroSearchResults", resourceCulture);
            }
        }
    }
}
