//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Panama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolTip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTip() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Panama.Resources.ToolTip", typeof(ToolTip).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This alert is currently enabled.
        /// </summary>
        public static string AlertEnabled {
            get {
                return ResourceManager.GetString("AlertEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the default author when creating new titles.
        /// </summary>
        public static string AuthorDefault {
            get {
                return ResourceManager.GetString("AuthorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the operation.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the list of titles to the clipboard.
        /// </summary>
        public static string CopyTitles {
            get {
                return ResourceManager.GetString("CopyTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract title from latest version.
        /// </summary>
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filters.
        /// </summary>
        public static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish filter(s) on the collection.
        /// </summary>
        public static string FilterCustom {
            get {
                return ResourceManager.GetString("FilterCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all filters to default.
        /// </summary>
        public static string FilterReset {
            get {
                return ResourceManager.GetString("FilterReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured parsing the message file..
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message file is in use, i.e. it has been selected as an entry for a submission message.
        /// </summary>
        public static string MessageInUse {
            get {
                return ResourceManager.GetString("MessageInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this title version down.
        /// </summary>
        public static string MoveTitleVersionDown {
            get {
                return ResourceManager.GetString("MoveTitleVersionDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this title version up.
        /// </summary>
        public static string MoveTitleVersionUp {
            get {
                return ResourceManager.GetString("MoveTitleVersionUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the app.
        /// </summary>
        public static string OpenWindowAbout {
            get {
                return ResourceManager.GetString("OpenWindowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open application settings.
        /// </summary>
        public static string OpenWindowSettings {
            get {
                return ResourceManager.GetString("OpenWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open tool window.
        /// </summary>
        public static string OpenWindowTool {
            get {
                return ResourceManager.GetString("OpenWindowTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage exclusions for orphan search.
        /// </summary>
        public static string OrphanExclusions {
            get {
                return ResourceManager.GetString("OrphanExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date this publisher was added to the database.
        /// </summary>
        public static string PublisherAdded {
            get {
                return ResourceManager.GetString("PublisherAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher wants an exclusive submission, i.e. does not accept simultaneous.
        /// </summary>
        public static string PublisherExclusive {
            get {
                return ResourceManager.GetString("PublisherExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter publisher list to display only publishers that are active, i.e. not flagged as a goner.
        /// </summary>
        public static string PublisherFilterActive {
            get {
                return ResourceManager.GetString("PublisherFilterActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter publisher list to display only publishers that are active and flagged for follow up.
        /// </summary>
        public static string PublisherFilterFollowup {
            get {
                return ResourceManager.GetString("PublisherFilterFollowup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter publisher list to display only publishers that currently have an open submission.
        /// </summary>
        public static string PublisherFilterHaveSub {
            get {
                return ResourceManager.GetString("PublisherFilterHaveSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter publisher list to display only publishers that are active and currently within a submission period.
        /// </summary>
        public static string PublisherFilterInPeriod {
            get {
                return ResourceManager.GetString("PublisherFilterInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter publisher list to display only publishers that are active and are a paying market.
        /// </summary>
        public static string PublisherFilterPaying {
            get {
                return ResourceManager.GetString("PublisherFilterPaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher currently has at least one submission that is active.
        /// </summary>
        public static string PublisherHasActive {
            get {
                return ResourceManager.GetString("PublisherHasActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher is currently in one of its submission periods.
        /// </summary>
        public static string PublisherInPeriod {
            get {
                return ResourceManager.GetString("PublisherInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date that the last submission was created for this publisher.
        /// </summary>
        public static string PublisherLastSubmission {
            get {
                return ResourceManager.GetString("PublisherLastSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher is a paying market.
        /// </summary>
        public static string PublisherPay {
            get {
                return ResourceManager.GetString("PublisherPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission count - the total number of times a submission has been made to this publisher.
        /// </summary>
        public static string PublisherSubmissionCount {
            get {
                return ResourceManager.GetString("PublisherSubmissionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission period count - the total number of submission periods that have been assigned to this publisher.
        /// </summary>
        public static string PublisherSubmissionPeriodCount {
            get {
                return ResourceManager.GetString("PublisherSubmissionPeriodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the link list, adding new entries and removing any stale entries.
        /// </summary>
        public static string RefreshLinkVerify {
            get {
                return ResourceManager.GetString("RefreshLinkVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset this window to its default size.
        /// </summary>
        public static string ResetWindow {
            get {
                return ResourceManager.GetString("ResetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all data (saves automatcially on exit).
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble the text in the text area.
        /// </summary>
        public static string ScrambleBegin {
            get {
                return ResourceManager.GetString("ScrambleBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste text from the clipboard into the text area to be scrambled.
        /// </summary>
        public static string ScramblePaste {
            get {
                return ResourceManager.GetString("ScramblePaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, words within the lines will be scrambled.
        /// </summary>
        public static string ScrambleWord {
            get {
                return ResourceManager.GetString("ScrambleWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published count - total number of items published.
        /// </summary>
        public static string SelfPublisherPublishedCount {
            get {
                return ResourceManager.GetString("SelfPublisherPublishedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send problem report. No personal information is included.
        /// </summary>
        public static string SendReport {
            get {
                return ResourceManager.GetString("SendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission is for a contest.
        /// </summary>
        public static string SubmissionContest {
            get {
                return ResourceManager.GetString("SubmissionContest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission has been accepted.
        /// </summary>
        public static string SubmissionFilterAccepted {
            get {
                return ResourceManager.GetString("SubmissionFilterAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission is active (has not yet received a response).
        /// </summary>
        public static string SubmissionFilterActive {
            get {
                return ResourceManager.GetString("SubmissionFilterActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission received a personal response.
        /// </summary>
        public static string SubmissionFilterPersonal {
            get {
                return ResourceManager.GetString("SubmissionFilterPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission received a try again response.
        /// </summary>
        public static string SubmissionFilterTryAgain {
            get {
                return ResourceManager.GetString("SubmissionFilterTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission is locked.
        /// </summary>
        public static string SubmissionLocked {
            get {
                return ResourceManager.GetString("SubmissionLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission is online.
        /// </summary>
        public static string SubmissionOnline {
            get {
                return ResourceManager.GetString("SubmissionOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the submission period to the entire year.
        /// </summary>
        public static string SubmissionPeriodAllYear {
            get {
                return ResourceManager.GetString("SubmissionPeriodAllYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize file names to title and version.
        /// </summary>
        public static string SynchonizeTitles {
            get {
                return ResourceManager.GetString("SynchonizeTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme is enabled for use.
        /// </summary>
        public static string ThemeEnabled {
            get {
                return ResourceManager.GetString("ThemeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default theme.
        /// </summary>
        public static string ThemeReset {
            get {
                return ResourceManager.GetString("ThemeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current submission count - the number of submissions that are still open for this title.
        /// </summary>
        public static string TitleCurrentSubmissionCount {
            get {
                return ResourceManager.GetString("TitleCurrentSubmissionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is flagged.
        /// </summary>
        public static string TitleFilterFlag {
            get {
                return ResourceManager.GetString("TitleFilterFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title has been published.
        /// </summary>
        public static string TitleFilterPublished {
            get {
                return ResourceManager.GetString("TitleFilterPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is flagged as ready.
        /// </summary>
        public static string TitleFilterReady {
            get {
                return ResourceManager.GetString("TitleFilterReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is currently submitted.
        /// </summary>
        public static string TitleFilterSubmitted {
            get {
                return ResourceManager.GetString("TitleFilterSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published count - the number of times this title has been published.
        /// </summary>
        public static string TitlePublishedCount {
            get {
                return ResourceManager.GetString("TitlePublishedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related count - the number of related titles this title contains.
        /// </summary>
        public static string TitleRelatedCount {
            get {
                return ResourceManager.GetString("TitleRelatedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission count - the total number of times this title has been submitted.
        /// </summary>
        public static string TitleSubmissionCount {
            get {
                return ResourceManager.GetString("TitleSubmissionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag count - the number of tags assigned to this title.
        /// </summary>
        public static string TitleTagCount {
            get {
                return ResourceManager.GetString("TitleTagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updated date for the latest version of this title.
        /// </summary>
        public static string TitleUpdated {
            get {
                return ResourceManager.GetString("TitleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version count - the number of versions that this title has.
        /// </summary>
        public static string TitleVersionCount {
            get {
                return ResourceManager.GetString("TitleVersionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word count - the number of words in the latest version of this title.
        /// </summary>
        public static string TitleWordCount {
            get {
                return ResourceManager.GetString("TitleWordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation creates a text file that has a list of all titles and their corresponding versions..
        /// </summary>
        public static string ToolTitleListDetail {
            get {
                return ResourceManager.GetString("ToolTitleListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation verifies that all files associated with title versions are present on disk and updates meta data that is stored in the database regarding each file, such as last updated date/time and word count..
        /// </summary>
        public static string ToolTitleMetadataDetail {
            get {
                return ResourceManager.GetString("ToolTitleMetadataDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin verification of links.
        /// </summary>
        public static string VerifyLinks {
            get {
                return ResourceManager.GetString("VerifyLinks", resourceCulture);
            }
        }
    }
}
